### ISSUE TITLE
`Jpeg decoding failed:Error parsing DQT segment. Reason:No quantization table for component Y` error on valid images

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#10]
I'm seeing this error happen on many images that are decoded fine by other decoders:

`Jpeg decoding failed:Error parsing DQT segment. Reason:No quantization table for component Y`

I have 1206 samples total, but here's a small subset so you can reproduce the issue: [zune-y-component.tar.gz](https://github.com/etemesi254/zune-image/files/10212671/zune-y-component.tar.gz)

Tested on commit 5877c2f2bf984f9f31b4883a1a4df628e5e0ae9b

**Comment by etemesi254** [comment]
Note, those images aren't spec compliant fully,the decoder was a bit strict on ordering of markers.

Relaxed it
