### ISSUE TITLE
zune-jpeg: Support extracting the ICC profile

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#101]
Based on my experience with [integrating](https://github.com/image-rs/image/pull/1876) `zune-jpeg` in `image`, the only missing feature required for completely replacing `jpeg-decoder` with `zune-jpeg` in `image` is extracting the ICC profile.

For reference, this is how it's implemented in jpeg-decoder:

https://github.com/image-rs/jpeg-decoder/blob/509ec661ef99b32df6d5d0e2049e912a49a3da65/src/decoder.rs#L201-L231

**Comment by etemesi254** [comment]
ICC chunk support, same implementation as jpeg-decoder. : https://docs.rs/zune-jpeg/0.3.14/zune_jpeg/struct.JpegDecoder.html#method.icc_profile

Exif chunk support :  https://docs.rs/zune-jpeg/0.3.14/zune_jpeg/struct.JpegDecoder.html#method.exif
