### ISSUE TITLE
Channel::new_with_length is not generally sound

### ISSUE THREAD

**Issue by HeroicKatora** [etemesi254/zune-image#106]
https://github.com/etemesi254/zune-image/blob/15e5d6c34dd51f9db6d8b3563da5c59e6d909131/zune-image/src/channel.rs#L169-L176

This virtuall allows access to `size` elements of type `T: Copy`. The memory however is still uninitialized, which makes any read UB. In particular you might instantiate: `T: &'static [u8]` or something funny like that. But note that even `u8` is _still_ UB by Rust's type definition. Only values of type `MaybeUninit<u8>` and similar are allowed to be uninitialized, not the primitive numeric types (this is in contrast to C).

**Comment by etemesi254** [comment]
Would this be solved with `alloc_zeroed` function?

**Comment by HeroicKatora** [comment]
Not alone, neither `T: Copy` nor `T: Default + 'static` makes any guarantee with regards to being allowed to initialized values from zero-bytes. `T: &'static [u8]` satisifies both. For more complicated bounds counter examples can be similarly constructed. Really only something explicit like `bytemuch::Zeroable` works.

It doesn't need to be a bound on the method, though! The main insight of [`image-texel`](https://docs.rs/image-texel/latest/image_texel/struct.Texel.html) is that we can make a zero-sized (and zero-cost) _token_ type that guarantees the bound on construction; but doesn't require mentioning the bound on every use.

**Comment by HeroicKatora** [comment]
My blog post, if you want to read some more ideas on how to use zero-sized tokens and some insights on bounds / enforcing type invariants <https://www.hardmo.de/article/2021-03-14-zst-proof-types.md>.

**Comment by etemesi254** [comment]
>Not alone, neither T: Copy nor T: Default + 'static makes any guarantee with regards to being allowed to initialized values from zero-bytes. T: &'static [u8] satisifies both. For more complicated bounds counter examples can be similarly constructed. Really only something explicit like bytemuch::Zeroable works.


There is also the option to constraint what types channel expects, i.e keep it to zeroable types like u8,u16 i32 etc.

I do not expect to expose it as a crate, and although `bytemuck` crate is pretty good for such things,but  I'm trying to watch  how big my Cargo.toml gets.

> It doesn't need to be a bound on the method, though! The main insight of [image-texel](https://docs.rs/image-texel/latest/image_texel/struct.Texel.html) is that we can make a zero-sized (and zero-cost) token type that guarantees the bound on construction; but doesn't require mentioning the bound on every use.

image-texel looks interesting, with only one problem for me, the definition of `Matrix<T>`, it contains a generic parameter T, I don't want that, would have been cool if it was just Matrix, and the `T` would be in places with    `new `and others that need a guarantee.

This is because my image type is just `Image`, not `Image<T>` , type pixels are just un-typed buffer of `[u8]`, metadata allows us to intepret those `[ u8]`  into something we can manipulate.

The problem comes with not messing up the intepretation

**Comment by etemesi254** [comment]
> My blog post, if you want to read some more ideas on how to use zero-sized tokens and some insights on bounds / enforcing type invariants https://www.hardmo.de/article/2021-03-14-zst-proof-types.md.

Zst's are nice and that's a well written blog post , kudos !!!

Sadly Rust doesn't allow such constructs

```Rust
pub struct Zst<T>(T);

struct A{
   zst:Zst<B>
}
```
Which for me may read,  create struct `A`, with inline generic `<B>` , but not exposed to the type system.

But `image-canvas` gets it right

**Comment by etemesi254** [comment]
Sorry,  Github closes commits referenced in messages when using Fixes:{issue}

**Comment by HeroicKatora** [comment]
> image-texel looks interesting, with only one problem for me, the definition of Matrix<T>, it contains a generic parameter T, I don't want that, would have been cool if it was just Matrix, and the T would be in places with new and others that need a guarantee.

Hm, yes, that is unfortunate and a beneficial property. The `TypeId` _is_ the dynamic variant of the zst `PhantomData<T>`. An interesting parallel to the non-zero-sized proof type section. Indeed, maybe it is _the_ minimal example for it. Regarding implementation of `Texel` it should also complent some of the interfaces quite neatly.

The design of `image-texel` considers that, if you want a dynamically typed version, you would hold an untyped `Image`  and change the layout to the target layout via [`Image::to_mut`](https://docs.rs/image-texel/latest/image_texel/image/struct.Image.html#method.to_mut). (With some higher-level wrapper if you want to _enforce_ this as an invariant). And `Matrix<T>` is just one of those convenience wrappers around with a specific `layout::Matrix<T>` enforced. Having all of those with "runtime"-type checks sounds like it could also fit conveniently.

**Comment by HeroicKatora** [comment]
To exemplify why `alloc_zeroed` does not in general fix this:

```rust
use core::num::NonZeroU8;
let mut img = Channel::new_with_length::<NonZeroU8>(1);
let channels = img.reinterpret_as::<NonZeroU8>().unwrap();
// May pass. what ?! Simple: this is UB.
assert_ne!(channels[0], channels[0]);
```

**Comment by etemesi254** [comment]
Quick question, any reason why the below code would fail?

```Rust
use std::any::{Any, TypeId};
use zune_image::channel::Channel;
let channel = Channel::new::<u8>();
assert_eq!(channel.type_id(),TypeId::of::<u8>());// fails
```

On commit 7056b0e

**Comment by HeroicKatora** [comment]
The method is named `get_type_id` in that particular commit. If it's something other than that, don't know.

**Comment by HeroicKatora** [comment]
I'm really not sure where to start for comprehensive soundness. It'd be easier if `unsafe` blocks regularly came with a safety comment, i.e. explaining _locally_ how the preconditions for the operations are supposed to provably hold. For instance, seems to depend on the impossibility to make new implementations of the trait `ZuneInts<T>` but that trait is neither `unsafe` nor is it documented.

It's not like I can't find any UB on first sight but that's _not_ because I can assure you there isn't any.

**Comment by etemesi254** [comment]
Added safety tags, in case you could spare some time, would love some other eyes.

And switched to using bytemuck
