### ISSUE TITLE
Zune Inflate: Fails to decode zlib-compressed binary data

### ISSUE THREAD

**Issue by johannesvollmer** [etemesi254/zune-image#109]
Hi! 

This binary data cannot be decoded. The error reported was `Mismatched Adler, expected 788192626 but found 2013846895`. The file seems to be valid though, because it can be opened by other decoders in the context of opening an OpenEXR file (see https://github.com/johannesvollmer/exrs/issues/210).

Here's the zlib-encoded bytes (.bin file):
[mismatched_adler.zip](https://github.com/etemesi254/zune-image/files/11016149/mismatched_adler.zip)

Any ideas what's wrong? Is this a zune inflate problem?

**Comment by etemesi254** [comment]
Yes it is, 

Thank you for reporting.

Working on a fix
