### ISSUE TITLE
JPEG XL: zune produces files that libjxl fails to decode

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#110]
After running `zune input.png output.jxl`, the resulting jxl file fails to decode with `djxl` v0.8.1 (latest upstream version).

2171 out of a total of ~50,000 input PNGs in my corpus are affected.

Here's a small sample of the affected files: [jxl-decode-failures.tar.gz](https://github.com/etemesi254/zune-image/files/11022230/jxl-decode-failures.tar.gz)

**Comment by etemesi254** [comment]
And also this should be fixed
