### ISSUE TITLE
JPEG XL: zune encodes some images incorrectly

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#111]
I've encoded these images from PNG to JPEG XL with `zune`, and they did not decode to the original image using `djxl` v0.8.1:
[jxl-encoded-incorrectly.tar.gz](https://github.com/etemesi254/zune-image/files/11031918/jxl-encoded-incorrectly.tar.gz)

Some appear to have their colors inverted, some are fully transparent, and a few are garbled.

Tested on commit c13f202933bafb80fb3600adc22881e5b4b42e57

**Comment by etemesi254** [comment]
Fixed some of them, there are some that don't work, specifically Grayscale+Alpha, filed an issue at https://github.com/libjxl/libjxl/issues/2331 since the encoder I was using also has bugs

**Comment by Shnatsel** [comment]
Nah it's fine, don't worry. I wouldn't be posting these images if I weren't OK with them being shared!

What I meant is, this can actually be included in a test suite and not cause issues for places that really care about copyright such as Debian.

**Comment by etemesi254** [comment]
This should be fixed
