### ISSUE TITLE
zune-jpeg: decode to BGR/BGRA image

### ISSUE THREAD

**Issue by CCnut** [etemesi254/zune-image#112]
How to decode jpeg image to BGR/BGRA image?

**Comment by etemesi254** [comment]
No way to do it internally.

Externally the following snippet may help

```Rust
// decode pixels to RGB format
let pixels = zune_jpeg::JpegDecoder::new(data).decode().unwrap();

// convert from rgb to bgr
for px_group in pixels.chunk_exact_mut(3){
     //  swap R with B
     std::mem::swap(&mut px_group[0],&mut px_group[3]);
}

// convert RGBA to BGRA
for px_group in pixels.chunk_exact_mut(4){
     //  swap R with B
     std::mem::swap(&mut px_group[0],&mut px_group[3]);
}
```
Do note, the swaps require data to be in that format

**Comment by CCnut** [comment]
Is there a plan to support BGR/BGRA color space output at any time?

**Comment by etemesi254** [comment]
What is your use case for BGR/BGRA output?

**Comment by CCnut** [comment]
Deep learning models require BGR/BGRA image input. Decoding directly to BGR/BGRA image can reduce conversion steps.

**Comment by etemesi254** [comment]
Done, but not yet released to crates io, so that will have to wait, I'll push it when I am pushing png (in about a week's time).

If i delay (~2 weeks) feel free to ping me

**Comment by etemesi254** [comment]
Done in `0.3.16`
