### ISSUE TITLE
Incorrect decoding of some real-world JPEG images

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#12]
At a quick glance, there seem to be at least two issues going on:

1. Quality degradation / pixelation on some greyscale or mostly-greyscale images
2. Incorrect recovery after RST marker in damaged images, so that everything following the RST marker is misaligned slightly
3. There are also some small images that are completely garbled, but that might be due to issue 1, not sure

Samples for reproducing the issues: [zune-divergences-3.tar.gz](https://github.com/etemesi254/zune-image/files/10213871/zune-divergences-3.tar.gz)

Tested on commit 5877c2f2bf984f9f31b4883a1a4df628e5e0ae9b

**Comment by etemesi254** [comment]
This one might take some time.

**Comment by Shnatsel** [comment]
I don't really care what happens to truncated images. No reason to try to fix them if this slows down decoding of valid images!

**Comment by etemesi254** [comment]
Issue no 3 should be fixed, took long because I was barking up the wrong tree, focusing on issue no 2 and 1 now.

**Comment by etemesi254** [comment]
1 is fixed, really appreciated this one, helped me find a nasty bug. Will update with benchmarks soon

**Comment by etemesi254** [comment]
Updated benchmarks(https://github.com/etemesi254/zune-image/blob/dev/zune-jpeg/Benches.md), we are slightly faster than mozjpeg which wraps  libjpeg-turbo but would be nice if you could test to ensure we're also correct now.  I'll be looking into the RST issue soon but I do feel we shouldn't be having huge divergences from imagemagick.

Thank you for your work.

Feel free to close this if there are no further issues

**Comment by Shnatsel** [comment]
Unfortunately this has regressed many images. Here's one example, but they all seem to show the same artifacts:

[philosoguar](https://user-images.githubusercontent.com/291257/210149396-22834c32-15dd-4c9b-8b5f-71c796735822.jpg)

This is my own drawing, I'm licensing it under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) so you could include it in tests.

**Comment by etemesi254** [comment]
Hi, could you check now under the dev branch.

Should hopefully be fixed.

I'm trying to figure out a way to ensure these regressions do not happen
again

**Comment by Shnatsel** [comment]
I can confirm this is fixed on the `dev` branch.

**Comment by Shnatsel** [comment]
Now the top divergences are on images where imagemagick gives up and outputs a blank image while zune-jpeg succeeds, so on this corpus zune-jpeg is now better than imagemagick!

I think there's just one last divergence:

![НЕБЕЗО~1](https://user-images.githubusercontent.com/291257/210154762-d0b7a762-49ab-4df3-aeba-ff1d0d2efb8a.JPG)

Which decodes into:

![НЕБЕЗО~1 JPG](https://user-images.githubusercontent.com/291257/210154771-a7c93022-7b8d-4ccc-af1e-1faa14155885.png)

**Comment by etemesi254** [comment]
It is reproducible, but sadly I can't say why it's like that.

Doesn't trigger an assert in debug builds, artifacts dissapear in load gimp->decode->save run.

Artifacts appear randomly?  

I do think the problem is in idct but then the issue is this type of image is the worst to debug with, as it is made up of multiple passes and any of those passes may cause errors, so this will take a while to resolve.
But in case of any such images,kindly share, especially small files, would love to test  them.

Nice to hear we are slighly better than imagemagick 🚀

**Comment by Shnatsel** [comment]
This is literally the only image I've seen with this kind of artifacts, out of the 50,000 I've tested.

**Comment by Shnatsel** [comment]
I've found one more problematic image.

Original:

![dv617059](https://user-images.githubusercontent.com/291257/213886375-8a66c1e2-fafb-40cf-b72e-7393d4f1210e.jpg)


Zune:

![dv617059 jpg ppm zune](https://user-images.githubusercontent.com/291257/213886378-96eee7f1-3c24-4201-9da0-333305d72bab.png)

Tested on commit 48ac1d1d85068683cc5f7ae0d71c67dbc5813c1f

**Comment by etemesi254** [comment]
> I've found one more problematic image.
> 
> Original:
> 
> ![dv617059](https://user-images.githubusercontent.com/291257/213886375-8a66c1e2-fafb-40cf-b72e-7393d4f1210e.jpg)
> 
> Zune:
> 
> ![dv617059 jpg ppm zune](https://user-images.githubusercontent.com/291257/213886378-96eee7f1-3c24-4201-9da0-333305d72bab.png)
> 
> Tested on commit [48ac1d1](https://github.com/etemesi254/zune-image/commit/48ac1d1d85068683cc5f7ae0d71c67dbc5813c1f)

Thank you, this help me confirm a certain path was doing the right thing.

Fixed in 3d1ba792f493622a85b1307d29ce7b1c03e61fdd but can't close this yet due to the above divergence

**Comment by Shnatsel** [comment]
I've confirmed that the lion image from https://github.com/etemesi254/zune-image/issues/12#issuecomment-1368274936 is fixed by #105; closing.
