### ISSUE TITLE
`de_filter_sub3_sse2` calls the inner function without a check

### ISSUE THREAD

**Issue by Lokathor** [etemesi254/zune-image#122]
https://github.com/etemesi254/zune-image/blob/main/zune-png/src/filters/sse4.rs#L198-L201

```rust
pub fn de_filter_sub3_sse2(raw: &[u8], current: &mut [u8])
{
    unsafe { defilter_sub3_sse2_inner(raw, current) }
}
```

On `x86_64` the `sse2` feature level is built into the arch, but on `x86` this is not *necessarily* an available feature. Currently, Rust's "i586" target is x86 only, and "i686" is actually x86+more. The module level guard (https://github.com/etemesi254/zune-image/blob/main/zune-png/src/filters/sse4.rs#L145-L146) is for x86 and `sse`, so the inner part of the `sse2` using function *could* be called when `sse` is enabled but `sse2` is not.

This is an extremely unlikely situation to be in.

Still, it's probably best to adjust the module level guard to check against `sse2` instead of just `sse`.

**Comment by Lokathor** [comment]
update to my above commentary: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/X86/X86.td#L97

apparently even x86_64 doesn't  *strictly* imply sse/sse2,

**Comment by etemesi254** [comment]
nice catch.
