### ISSUE TITLE
Expand with alpha channel during decoding

### ISSUE THREAD

**Issue by daxpedda** [etemesi254/zune-image#123]
This is very useful for loading textures into a GPU.

See https://github.com/image-rs/image-png/issues/239.

**Comment by etemesi254** [comment]
seems trivial

but question, what's the expected output when image is in grayscale? should we do grayscale+ alpha?

**Comment by daxpedda** [comment]
> should we do grayscale+ alpha?

Yes. Maybe expanding from Grayscale to RGB could be a different setting, but Greyscale + Alpha is still very useful for GPUs.

**Comment by daxpedda** [comment]
That is technically true, but there are texture formats with 16 bits per pixel, which would fit a Grayscale + Alpha (e.g. [`rg8uint`](https://www.w3.org/TR/webgpu/#dom-gputextureformat-rg8uint)). In comparison, there is no texture format that can fit 24 bits per pixel, which would be needed for RGB without Alpha.

**Comment by Lokathor** [comment]
GL and VK both support RGB without alpha. I'm very surprised that wgpu does not.

But if you're willing to swizzle your colors in the shader i won't stop you from using `rg8`

**Comment by daxpedda** [comment]
> GL and VK both support RGB without alpha. I'm very surprised that wgpu does not.

That is what I found out too, but after some research and experiments I found that RGB textures are not supported on most devices, see https://vulkan.gpuinfo.org/listlineartilingformats.php.

More research revealed that OpenGL supports these textures because the spec requires it (I didn't confirm this myself), but internally drivers just convert them.

**Comment by etemesi254** [comment]
should it be premultiplied or non ptemultiplied alpha?

**Comment by etemesi254** [comment]
fwiw the implementation will be slower than normal conversions


there is no way to deeply integrate it hence it hass to be done as a separate pass, but done per row.

For other things such as gamma correction and premultiplied vs non ptemultiplied they are currently  performed in the zune-image crate.

**Comment by etemesi254** [comment]
> pre-multiplied alpha with only 8 bits per channel will lose some precision such that you can't "go back" to straight alpha, but also GPU interpolation only works right with pre-multiplied alpha so personally I'd advise people to use it.
> 

premultiplied alpha is lossy, so as long as alpha is zero you can never go back


Also handling premultiplied alpha in interleaved format is slow, it's not easily vectorized and you want integers to round up so you need to perfom it in `n +1` bits where n is maximum number of bits for that type(8 for u8) , it's faster to do alpha premultiplication when image is in planar. That's why such things are done independent of codecs via zune-image crate


the best I can do here is to convert to srgb encoded rgb+a or luma+a for rgb or luma respectively in a fast enough way

**Comment by Lokathor** [comment]
I'd just like to re-state what i think daxpedda is saying: if you need a particular image conversion then *that's what you need*, and it doesn't matter if SIMD is possible or not. Any output that doesn't do the conversion the user needs isn't useful. Usefulness beats speed.

**Comment by daxpedda** [comment]
This issue was specifically to optimize that specific conversion, if possible.

But yes, what @Lokathor said.

**Comment by etemesi254** [comment]
Usage 

You set the option for add_alpha_channel(true)

```Rust
 use zune_core::options::DecoderOptions;
 use zune_png::PngDecoder;
 // set option to add alpha channel
 let options = DecoderOptions::default().png_set_add_alpha_channel(true);
 // use the above option to decode
 let mut decoder = PngDecoder::new_with_options(&[],options);

 decoder.decode().unwrap();
 // the colorspace will always be have an alpha
 assert!(decoder.get_colorspace().unwrap().has_alpha())
```

**Comment by daxpedda** [comment]
Thank you, will test is and report back.

**Comment by etemesi254** [comment]
will be a bit tricky though, you need to clone the repo and use the local
clone as your png decoder since for it to work you need both unreleased
zune-core and zune-png

**Comment by Lokathor** [comment]
if you clone the repo and set a `path` dependency in Cargo.toml it should be a fairly easy switch.

**Comment by daxpedda** [comment]
You can just use:
```toml
[patch.crates-io]
zune-png = { git = "https://github.com/etemesi254/zune-image" }
```

I tried it, works perfectly, thanks!

**Comment by etemesi254** [comment]
Should be in `0.2.1` of  `zune-png` in crates io
