### ISSUE TITLE
Where is Y-flipping?

### ISSUE THREAD

**Issue by kvark** [etemesi254/zune-image#130]
Sorry if I missed it! I'm looking at `zune-imageproc` code, and I'm seeing:
  - "flip"  - flips both horizontally and vertically at the same time
  - "flop" - flips only horizontally

Is this an intentional omission that there is no purely vertical flip?

**Comment by etemesi254** [comment]
hi

sorry for late reply 

currently there is no vertical flip in zune-imageprocs yet but there is code for vertical flip in zune-ppm (decode.rs 690 (sorry typing in phone can't quote directly)) so porting it is not a problem

**Comment by etemesi254** [comment]
Added it  in 8927832

![image](https://github.com/etemesi254/zune-image/assets/24320659/7ac3eb77-b656-40ec-8d98-e4b10cf931ca)


From `zune-imageprocs`it's `horizontal_flip` method, in `zune-image` it's `HorizontalFlip` and in the command line it's `--h-flip`

Will improve docs in later iterations

(Also a minor nitpick, i saw you are using resize from zune-imageprocs, it currently does nothing as I have yet to implement it correctly(linear light pre-multiplied resizing))

**Comment by kvark** [comment]
@etemesi254 this doesn't look right. I need vertical flipping, while the one just added is *another* horizontal one? As far as I see from the docs, the `flop()` is already there for the horizontal flips.

> (Also a minor nitpick, i saw you are using resize from zune-imageprocs, it currently does nothing as I have yet to implement it correctly(linear light pre-multiplied resizing))

Aha, thanks for the heads up! I'm not using the result of this operation either just yet, but will definitely need it soon.

**Comment by etemesi254** [comment]
Hi, my bad, happened to misinterpret the request

If it's something like the below one, the tagged commit above this message just added it

![image](https://github.com/etemesi254/zune-image/assets/24320659/1339e342-7f83-4b69-a527-1a5ad234b280)

**Comment by kvark** [comment]
Perfect, thanks!
