### ISSUE TITLE
Follow the Rust API Guidelines naming

### ISSUE THREAD

**Issue by emilk** [etemesi254/zune-image#137]
[The Rust API Guidelines](https://rust-lang.github.io/api-guidelines/about.html) are followed by most Rust libraries, and makes using a library easier and more familiar.

One thing I've noticed in `zune` is that it uses the `get_` prefix in a lot of places, e.g. `get_dimensions`. Nothing in the standard library does this; see <https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter>. So `decoder.dimensions()` would be more idiomatic.

Of course, this is your library and your choice, but following the broader standards can help attract more users and contributors to these excellent crates!

(To that end I would also vote fore using the standard cargo format, though I doubt that will be well-received suggestion 😄)

**Comment by etemesi254** [comment]
I honestly never new about the guidelines.

Nice 
> One thing I've noticed in `zune` is that it uses the get_ prefix in a lot of places, e.g. `get_dimensions.` Nothing in the standard library does this; see https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter. So `decoder.dimensions()` would be more idiomatic.

Okay most opinions are understandable, but  how are setters handled, could not find it in the guidelines you shared?  

> (To that end I would also vote fore using the standard cargo format, though I doubt that will be well-received suggestion 😄  )

Is this documented anywhere,I can only infer this via rerun and cargo repos, never heard of it.

If it helps in readability, it's fine by me, though I have a particular disdain for how git handles file moves and I have botched enough git moves to last me a lifetime, (e.g this repo does not have the full commit history for zune-jpeg messed it up so bad I had to just give it away https://github.com/etemesi254/zune-image/commit/3c158d6a0367d4bd8bae9edd3caac2fc97f485a6)

**Comment by emilk** [comment]
The standard style for setters and getters in Rust is:

```
impl Foo {
    pub fn version(&self) -> i32 { … }
    pub fn set_version(&mut self, version: i32) { … }

    pub fn name(&self) -> &str { … }
    pub fn set_name(&mut self, name: String) { … }
}
```

As for `cargo fmt`: just remove [custom `rustfmt.toml`](https://github.com/etemesi254/zune-image/blob/dev/rustfmt.toml) and run `cargo fmt` to get the standard Rust code style. Yes, it will be a big diff :)

**Comment by etemesi254** [comment]
Commit: a5e0460621c65a3416a4280bf80eda76f79b8d13  (and some others) changed some setters and getters

Some `git filter-repo` moved things around to match the cargo style

There was a commit also fixing the source code format, I didn't fully remove the `rustfmt.toml` but made it more compatibly with normal formatting.

I think that was all I did
