### ISSUE TITLE
License questions for zune-inflate

### ISSUE THREAD

**Issue by werdahias** [etemesi254/zune-image#139]
Cargo.toml mentions that this crate is tri-licensed while LICENSE.md mentions only Apache-2.0 and MIT. 
Also there is no mention of the author in the license files. 
Does this mean zune-inflate is tri-licensed ?

**Comment by etemesi254** [comment]
> Does this mean zune-inflate is tri-licensed ?

Yes, all crates under `zune` are tri-licensed
