### ISSUE TITLE
zune-jpeg: panic on crafted image found by fuzzer

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#151]
Decoding the following image causes a panic:  [crash-f15a1f750cff110e0c8a307d914e63aca5c28e33](https://github.com/etemesi254/zune-image/assets/291257/812435e7-c83f-4335-bfb8-1668b1208220)

```
thread '<unnamed>' panicked at zune-image/crates/zune-jpeg/src/worker.rs:411:13:
assertion `left == right` failed
  left: 65536
 right: 32768
```

Tested on commit b1ff285c0d96d4209deb7ead8768f80d7c522a82

**Comment by etemesi254** [comment]
Thanks for reporting,

I am aware of this, and have been thinking of a way to fix it, will land a fix in some few days

**Comment by etemesi254** [comment]
Sorry for the long delay, had a pretty busy month, but should be fixed

I tried to get it to decode to whatever libjpeg-turbo does, but that became too messy and made me remove some asserts that I need to be present. In case someone reports a real image, I will probably need to revisit, but for now better not crash people's code
