### ISSUE TITLE
DecoderOptions::new_fast and DecoderOptions::new_cmd are the same

### ISSUE THREAD

**Issue by chloekek** [etemesi254/zune-image#156]
The following succeeds:

```rust
assert_eq!(
    format!("{:?}", DecoderOptions::new_fast()),
    format!("{:?}", DecoderOptions::new_cmd()),
);
```

Is this intentional?

**Comment by etemesi254** [comment]
It is a consequence of what both options mean

`new_fast` was meant for fast execution and

`new_cmd` was meant for error ressilience, used by the `zune-bin` library

It happens that for us to be fast we ignore errors and skip checks, hence making them the same

see https://github.com/etemesi254/zune-image/blob/dev/crates/zune-core/src/options/decoder.rs for comments

**Comment by chloekek** [comment]
Thanks!
