### ISSUE TITLE
Build failure with `separate_color_and_alpha_ref`

### ISSUE THREAD

**Issue by kvark** [etemesi254/zune-image#159]
>error[E0599]: no method named `separate_color_and_alpha_ref` found for reference `&Frame` in the current scope
   --> /home/kvark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zune-imageprocs-0.4.14/src/composite.rs:110:39
    |
110 | ...                   src_frame.separate_color_and_alpha_ref(colorspace).unwrap();
    |

**Comment by kvark** [comment]
looks like it's just a missing version requirement from imageprocs to image. The function was added in https://github.com/etemesi254/zune-image/commit/6f319acf9bc3a11e60366f547876d2058bf6cbc9

**Comment by etemesi254** [comment]
is this the version in crates-io or are you dependent on the `dev` branch?

**Comment by kvark** [comment]
This if from crates.
