### ISSUE TITLE
Build failure with `ColorSpace` 

### ISSUE THREAD

**Issue by kvark** [etemesi254/zune-image#160]
> error[E0599]: no variant or associated item named `HSL` found for enum `ColorSpace` in the current scope
   --> /home/kvark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zune-image-0.4.14/src/core_filters/colorspace/conversion_functions.rs:325:48
    |
325 |     assert_eq!(image.colorspace(), ColorSpace::HSL);
    |                                                ^^^ variant or associated item not found in `ColorSpace`

Missing patch version requirement from zune-image to zune-core

**Comment by etemesi254** [comment]
same question as before. might be me who may have missed to upgrade some dependencies (Sorry if that's the case)

**Comment by kvark** [comment]
yes, this is from crates

**Comment by etemesi254** [comment]
Hi could you confirm that this is fixed in latest release?

Sorry for the failure, I am still not familiar with semver

**Comment by kvark** [comment]
Looks like it's good now, thanks!
