### ISSUE TITLE
zune_imageprocs::resize is marked as broken

### ISSUE THREAD

**Issue by hillin** [etemesi254/zune-image#165]
https://docs.rs/zune-imageprocs/0.4.15/zune_imageprocs/resize/index.html

Is there an ETA when this will get fixed?

We are tempted to replace image-rs with zune-image in our project, this is currently the biggest dealbreaker.

**Comment by etemesi254** [comment]
Hi, it does work

I just implemented the bilinear one, which is fast but lower quality, hence why marked as broken, images will appear really choppy.

I am working on finalizing the other algorithms probably somewhere this month as i prepare for a 0.5 release somewhere in April
