### ISSUE TITLE
Decoding attached hdr file is not work well

### ISSUE THREAD

**Issue by piaoger** [etemesi254/zune-image#166]
I tried sample hdr files, it works fine  to read both "#?RADIANCE" and ""#?RGBE".  While it does not work with below hdr file which is generated by vray renderer.

[hdr.zip](https://github.com/etemesi254/zune-image/files/14610771/hdr.zip)

**Comment by etemesi254** [comment]
Thanks for the report

Looking into it

**Comment by etemesi254** [comment]
Hello, this was fixed in the latest dev. Closing it for now

Thank you for reporting

**Comment by etemesi254** [comment]
https://github.com/etemesi254/zune-image/commit/a3605beb9108bc98d7e7b073f8b4ac6db70d2fd7?diff=split&w=0


I made a mistake of adding the fix on top of a big rewrite because I wasn't sure if i fixed it so sorry for the messy commit, but if you see crates-zune/hdr/src/decoder there is a change in `decompress` and another change in line 344

**Comment by etemesi254** [comment]
I am yet to make a release to crates.io , but  https://github.com/etemesi254/zune-image/releases/tag/v0.5.0-rc0 contains binaries that can be used to test

you can use

`zune -i image.hdr --view --trace` to decode a hdr file save ut as uncompressed png in the temp folder and open it in your default png opener. Note I've tested it on linux , `-- view` may not work on other os.

You can use `zune -i image.hdr -o image.png` to convert images quickly

**Comment by etemesi254** [comment]
Hi, you made a mistake in 
```rust
    let mut output = vec![0;encoder.expected_buffer_size().unwrap()];
    let size = encoder.encode(&mut output).unwrap();
    output.truncate(size);
```
You allocated space and then passed that to the writer, in the new api, we continue writing after whatever was allocated.
It would be better if you use the following
```rust
 let mut output = Vec::with_capacity(encoder.expected_buffer_size().unwrap());
 let size = encoder.encode(&mut output).unwrap();
```

Or if you are going to write to a file, you can just pass the file, it accepts anything that implements `Write` trait

```rust
// using buffered writes to be on the safe side, it may be a perf hit or gain, please benchmark if it matters
let mut file = std::io::BufWriter(std::fs::File::create(&to).unwrap());
encoder.encode(&mut file).unwrap();

```

**Comment by etemesi254** [comment]
Thanks for the remainder, will do that for that and other affected encoders.

**Comment by etemesi254** [comment]
Hi, I may not understand you, do you mean there is still an issue or?

**Comment by etemesi254** [comment]
Hi, pushed `0.5.0-rc0` in case you had to manually link to the repo.

The command 

```sh
./zune -i /home/caleb/Downloads/vray.hdr --trace  -o ~/hello.hdr
```

Works for me 
![image](https://github.com/etemesi254/zune-image/assets/24320659/3a29c305-6e63-430f-b8dd-9213b62ccd5d)


It decodes and then reencodes the app which is what I expect

And using the sample code you provided, 

```rust
#[cfg(test)]
mod tests {

    use std::collections::HashMap;
    use std::io::Write;
    use std::path::Path;

    use zune_core::bit_depth::BitDepth;
    use zune_core::colorspace::ColorSpace;
    use zune_core::options::EncoderOptions;

    use zune_hdr::{HdrDecoder, HdrEncoder};

    pub fn rewrite_hdr<P: AsRef<Path>>(from: P, to: P) {
        let f = std::fs::File::open(&from).unwrap();
        let file_data = std::io::BufReader::new(f);
        let mut data = HdrDecoder::new(file_data);
        let pix: Vec<f32> = data.decode().unwrap();

        let (w, h) = data.dimensions().unwrap();
        let meta = data.metadata();

        let mut headers: HashMap<String, String> = HashMap::new();
        for (k, v) in meta {
            headers.insert(k.clone(), v.clone());
        }

        // setup options, we specify width and height here which are needed,
        // colorspace must always be rgb and the depth is f32,
        let encoder_opts = EncoderOptions::new(w, h, ColorSpace::RGB, BitDepth::Float32);
        let mut encoder = HdrEncoder::new(&pix, encoder_opts);
        encoder.add_headers(&headers);

        let mut output = vec![];
        let size = encoder.encode(&mut output).unwrap();
        output.truncate(size);

        let mut file = std::fs::File::create(&to).unwrap();
        file.write_all(&output).unwrap();
    }

    #[test]
    fn test_rewrite_hdr() {
        rewrite_hdr("/home/caleb/Downloads/vray.hdr", "/home/caleb/vray2.hdr");
    }
}
```

It doesn't generate a black image for me

**Comment by etemesi254** [comment]
Hi, could you upload the output of 

```shell
./zune -i /home/caleb/vray2.hdr --trace  -o ~/vray-resaved.hdr

```
`zune` is found from cloning this repository and running `cargo build --release`  and `cd ./target/release`

It generates the same image  for me (attached below)

[vray-resaved.zip](https://github.com/etemesi254/zune-image/files/15041139/vray-resaved.zip)

**Comment by etemesi254** [comment]
Hi, sorry for such a long delay responding to this, I remember there being a problem with a certain image, was it the `vray-2.zip` file because debugging with that doesn't indicate any issues on my side, can you confirm that?

**Comment by etemesi254** [comment]
E.g decoding and increasing the exposure by 500x gived me

![vray](https://github.com/etemesi254/zune-image/assets/24320659/5ed706ca-7008-4b58-8301-a678332c9314)


Command is 
```shell
./zune  -i ~/Downloads/vray.hdr --trace --exposure 500 -o ~/Downloads/vray.jpg

```
