### ISSUE TITLE
Adhere to API guidelines on method naming

### ISSUE THREAD

**Issue by djc** [etemesi254/zune-image#169]
In particular, I noticed a bunch of `get_()` prefixes:

- `Decoder::get_options()`
- `Decoder::get_output_colorspace()`
- `Decoder::get_input_colorspace()`

https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter

(I also note that you write `colorspace` in one word in snake case, but `ColorSpace` in two words in Pascal case.)

**Comment by etemesi254** [comment]
Version `0.5.0-rc0` removes most definitions of `get` across the library.
