### ISSUE TITLE
Add ICC profile to metadata

### ISSUE THREAD

**Issue by SalOne22** [etemesi254/zune-image#178]
`JpegDecoder` and `PngInfo` support extracting icc profile from image. It would be useful to add the icc profile as an Option field in the metadata structure. This adds the ability to write and process an icc profile using something like lcms2. It will also be good if there is support for writing icc profiles using default encoders.

**Comment by etemesi254** [comment]
Done via https://github.com/etemesi254/zune-image/commit/185e36201785334fcb50195e5f6f95c93eeba805.

But currently no parsing support is planned.

Added to the following decoders
  - jpeg, png and jxl.
 The rest I'm not sure of their ICC support
