### ISSUE TITLE
Panic: zune-jpeg

### ISSUE THREAD

**Issue by ava57r** [etemesi254/zune-image#188]
Hello
I found this picture
![tBtdPVJPy2M](https://github.com/etemesi254/zune-image/assets/20382553/fc4c2798-99e5-4c84-a3f1-bd5dde132dce)

i run

```rust
use zune_jpeg::JpegDecoder;
use std::fs::read;

fn main() {
    // load some jpeg data
    let data = read("tBtdPVJPy2M.jpg").unwrap();
    // create a decoder
    let mut decoder = JpegDecoder::new(&data);
    // decode the file
    let _pixels = decoder.decode().unwrap();
```

I got

```sh
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zune-jpeg-0.4.11/src/worker.rs:411:13:
assertion `left == right` failed
  left: 12800
 right: 6400
```

**Comment by etemesi254** [comment]
Hi, the version `0.5.0-rc0` has a fix for this, but since I  changed the read api to accept more io types it's a breaking change and I don't have the time to backport it to 0.4.0.

Closing it as fixed
