### ISSUE TITLE
v0.5.0-rc0 jpeg decoder does not work when input is a Cursor (rather than a ZCursor)

### ISSUE THREAD

**Issue by Murad-Awad** [etemesi254/zune-image#191]
Link to thread in image-rs/image: https://github.com/image-rs/image/pull/2198#issuecomment-2062088926. Basically, when using a PR by fintelia which makes use of a Cursor input as an input to `JpegDecoder`, when subsequently running `.decode()`, the jpeg was decoded in a lossy way (some pixels got lost). The image used for testing is attached. Surprisingly, this same issue didn't occur when using an integration I provided here: https://github.com/image-rs/image/pull/2209, which wraps a Vec created by reading the original input (which uses a Cursor) into a `ZCursor`. 
The image used for testing: ![black_10_10](https://github.com/etemesi254/zune-image/assets/20307403/5a329b94-e53a-4d81-bc01-560a23e34166)
The corrupted output after reading the decoded version (zoomed close up screenshot): 
![Screenshot 2024-04-15 at 4 55 52 PM](https://github.com/etemesi254/zune-image/assets/20307403/22165170-5161-42bc-95ec-b08e49c026e8)

**Comment by etemesi254** [comment]
Hi, I can't see the attached image

**Comment by Murad-Awad** [comment]
> Hi, I can't see the attached image

It's really small but it's the tiny black box right after the colon!

**Comment by Murad-Awad** [comment]
for reference it's just a 10x10 black image

**Comment by etemesi254** [comment]
Sorry I have dark theme enabled :), will look into it
