### ISSUE TITLE
`zune-bmp` decode doesn't support icc feature

### ISSUE THREAD

**Issue by Mikachu2333** [etemesi254/zune-image#195]
When input a pic which has an icc profile and decode with `zune-bmp`, the color will be changed incorrectly as the following link shows.

https://github.com/SalOne22/rimage/pull/208#pullrequestreview-2039320505

**Comment by etemesi254** [comment]
I am yet to find sources on how to read ICC profiles from bmp, the microsoft docs is a bit vague on that.

But working on it

**Comment by Mikachu2333** [comment]
thanks for answer!

**Comment by etemesi254** [comment]
`v0.5.0-rc4` should have a icc. It may still not be correct because I don't yet have an ICC reader hence couldn't check if it's fully working, so if it works for your case, please confirm here
