### ISSUE TITLE
missing license texts for MIT and Apache-2.0 (and Zlib) from distributed crates

### ISSUE THREAD

**Issue by decathorpe** [etemesi254/zune-image#203]
I noticed that the crates that are published on crates.io from this project don't contain any license texts - upon further investigation, it looks like the project doesn't contain the MIT or Apache-2.0 license texts at all.

Both the MIT and Apache-2.0 licenses require that (re)distributed sources contain a copy of the license text, so it would be great if the MIT and Apache-2.0 license texts could actually be included in the repository, and all license files linked into crates so that cargo includes them when running `cargo publish`.

If a Pull Request to add the standard license texts for MIT and Apache-2.0 and adding symbolic links to include all license texts in published crates (as required) would be acceptable, I can work on that.

---

To provide some context: I am the maintainer of the packages for the `image` crate in Fedora Linux, and the update from image v0.24 to v0.25 added new dependencies on `zune-jpeg` and `zune-core`. I noticed that neither crate includes license texts for either MIT, Apache-2.0, nor Zlib.

The fact that the license texts are currently missing is currently blocking me from packaging them for Fedora Linux and updating the `image` crate (i.e. the Zlib license text is present in the repo but missing from published crates, and MIT and Apache-2.0 license texts are missing from the repo entirely).

**Comment by etemesi254** [comment]
Hi , sorry missed that, they are in the top level repository, since the library is a group of crates

is it required to be in all crates?

If so a PR would be welcome

**Comment by decathorpe** [comment]
> they are in the top level repository, since the library is a group of crates

Nope, license texts for MIT and Apache-2.0 are not present at all - https://github.com/etemesi254/zune-image/blob/dev/LICENSE.md is just a copyright statement but not a license text (it's also outdated since you added the Zlib option).

> is it required to be in all crates?

Yes, license texts are technically required to be present in all published crates. They *are* redistributed separately after all (via crates.io), so the fact that they originate in the same git repository is not really relevant.

> If so a PR would be welcome

Thanks, I will work on that later today.

**Comment by etemesi254** [comment]
I believe this is now okay
