### ISSUE TITLE
Clang Error: "No Such File or Directory" for Existing Object Files During Cross-Compilation to aarch64-linux-android

### ISSUE THREAD

**Issue by mtobin-tdab** [etemesi254/zune-image#204]
I am trying to compile a Cargo project which has a dependency on `zune-jpeg = "0.4.11"`. My compile target is `aarch64-linux-android`.

I am encountering a clang error stating that certain files cannot be found:

```
= note: clang: error: no such file or directory: '.../test-zune-jpeg/target/aarch64-linux-android/release/deps/zune_jpeg-a5d391d7e7e200c8.zune_jpeg.efc976ba686ba3d6-cgu.0.rcgu.o'
          clang: error: no such file or directory: '.../test-zune-jpeg/target/aarch64-linux-android/release/deps/zune_jpeg-a5d391d7e7e200c8.zune_jpeg.efc976ba686ba3d6-cgu.1.rcgu.o'
          clang: error: no such file or directory: '.../test-zune-jpeg/target/aarch64-linux-android/release/deps/zune_jpeg-a5d391d7e7e200c8.zune_jpeg.efc976ba686ba3d6-cgu.2.rcgu.o'
          clang: error: no such file or directory: '.../test-zune-jpeg/target/aarch64-linux-android/release/deps/zune_jpeg-a5d391d7e7e200c8.zune_jpeg.efc976ba686ba3d6-cgu.3.rcgu.o'
          clang: error: no such file or directory: '.../test-zune-jpeg/target/aarch64-linux-android/release/deps/zune_jpeg-a5d391d7e7e200c8.zune_jpeg.efc976ba686ba3d6-cgu.4.rcgu.o'
```

Despite the files existing in the specified directory, clang reports that they cannot be found.

To help diagnose and resolve this issue, I am attaching a zip file containing the project. Please follow these steps to recreate the failure:

- Unzip the attached project.

- Update the linker path in `.cargo/config.toml` to point to your Android NDK.

- Run the build command:
```
cargo build --target aarch64-linux-android --release --verbose
```
Any insights or suggestions to resolve this linking issue would be greatly appreciated.

[test-zune-jpeg.zip](https://github.com/etemesi254/zune-image/files/15389520/test-zune-jpeg.zip)

**Comment by etemesi254** [comment]
could you try with a `0.5.*-rc` build, 0.4 had a lib=dynlib which may have been problematic

**Comment by etemesi254** [comment]
Any updates on this?

**Comment by mtobin-tdab** [comment]
@etemesi254 Yes that compiles. Thanks!
