### ISSUE TITLE
zune-jpeg hits panics due to out of range in mcu code

### ISSUE THREAD

**Issue by tistatos** [etemesi254/zune-image#207]
Attached image causes panics on released version of zune-jpeg and on dev-branch.

It panics here:
```
panicked at zune-image/crates/zune-jpeg/src/mcu.rs:377:44:
range end index 5616 out of range for slice of length 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If i examine the file info in macos 14.3.1 it will detect that it uses CMYK, but zune-jpeg reports `YCbCr` however the file reports via `exiftool` that it has 4 color components. And in the mcu code of the jpeg there is a 4 colorcomponent vector, but its length is 0.

If possible it would be nice to not have the code to panic. A suggestion would be to add a check to determine if the length of a color component is larger than 0  

**Note:** The file has probably been converted from a tif into jpg using an online service by a colleague of mine. I'm still investigating what service was used and try to recreate the issue with a new file.

![too_many_components](https://github.com/etemesi254/zune-image/assets/2827554/8f63cbe2-e8bf-4ef2-8ce4-ab31a57edde5)

**Comment by etemesi254** [comment]
Hi, this is an error on my part, ideally the library shouldn't panic, so that's a bug. Looking into it

**Comment by etemesi254** [comment]
Fixed now,  thanks for reporting, in case you have a smaller image with the same characteristics, would love if you could share so that I can add it to the test-suite (The shared image is too big to warrant an addition)
