### ISSUE TITLE
Error decoding SOF Marker, Number of components cannot be zero with thermal JPEG

### ISSUE THREAD

**Issue by AlexanderProd** [etemesi254/zune-image#208]
I'm trying to decode a jpeg image from a thermal camera, the binary information is retrieved from `exiftool`.

```rs
let binary = Command::new("exiftool")
            .arg("-b")
            .arg("-RawThermalImage")
            .arg(temp_file.path())
            .output()?
            .stdout;

let format = guess_format(&binary)?;
assert_eq!(format, ImageFormat::Jpeg);

let image = load_from_memory_with_format(&binary, ImageFormat::Jpeg)?;

let mut decoder = JpegDecoder::new(&buffer);
let decoded = decoder.decode()?;
```

While guessing the image format using the `guess_format` function from the `image` crate works, the `decode` function from the `zune-jpeg` crate fails to decode the binary file and returns the error 

```
Error decoding SOF Marker, Number of components cannot be zero.
```

I'm quite certain that the jpeg data is valid and not corrupted.
When I do the same operation in python, decoding the result from `exiftool`, using the `decode` function from the [libjpeg](https://pypi.org/project/pylibjpeg-libjpeg/) library it works.

I have created a [repository](https://github.com/AlexanderProd/decode-thermal-jpeg-rust) where you can recreate it, with the binary file included and also the working python script.

I'm using zune-jpeg version 0.4.11 with rust 1.77.2 on macOS 14.5.

**Comment by etemesi254** [comment]
looking into it

would be better if you attach the jpeg image here for easy debugging

**Comment by AlexanderProd** [comment]
> looking into it
> 
> would be better if you attach the jpeg image here for easy debugging

I have extracted it from a CSQ file, basically a video file of thermal images. But extracting this individual one from the CSQ one needs a couple more steps, I only have it done it python yet though.

**Comment by AlexanderProd** [comment]
I have tried libjpegturbo too but it didn’t work, so far I haven’t found a rust crate which could decode it. But I’m wondering why the python [libjpeg](https://pypi.org/project/pylibjpeg-libjpeg/) package can decode it. They don’t state anything special about their package.

**Comment by etemesi254** [comment]
Ah now I see, tldr, it's only libjpeg and rust jpeg-decoder that can decode that image

The image type is a lossless jpeg, marker formats in jpeg are `0xFF{1 byte MARKER}` so the decoder encounters a `0xFFF7` marker when decoding, according to this article, https://www.disktuna.com/list-of-jpeg-markers/, `0xfff7` is the marker that indicates the image is a lossless image, we currently don't support such images so yes,we can't decode it.

Sorry

**Comment by AlexanderProd** [comment]
@etemesi254 
Thank you for your elaborate reply, that is very helpful indeed. 

Unfortunately [jpeg-decoder](https://crates.io/crates/jpeg-decoder) also fails to decode the image. 

I'm wondering If I need to write my own JPEG-LS decoder in rust. 😅

**Comment by etemesi254** [comment]
It's actually not that complicated of a format, (ffmpeg has a 500 loc implementation https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/jpeglsdec.c) so go for it (ffmpeg can decode it)

I currently don't have plans to support it, maybe one day, but not today.

All the best
