### ISSUE TITLE
I've backported zune-jpeg fixes to 0.4.x so you don't have to

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#215]
(Github won't let me create a PR that would have a sensible diff, so I'm opening an issue instead)

This is my proposal for `zune-jpeg` 0.4.12, ready to be published to crates.io: https://github.com/Shnatsel/zune-image/tree/zune-jpeg-4.12

Diff against v0.4.11: https://github.com/etemesi254/zune-image/compare/add9ba71c9e29665ca65003ead12f85d25d763a7...Shnatsel:zune-image:zune-jpeg-4.12?expand=1

This should fix the decoding panics that people keep encountering on v0.4.11.

I've created it by starting with 0.4.11 and cherry-picking commits 1f943d81b1eb189535abfd2afac8f017c57164f3, efb4cb094a0ba27616c9d4a0909cd7b052e2a72a, ac18d0bf2a672a8ee57653bbae1c4c2d8fafbba0, 0938b48b0ed6374a83ba8f80d2e4ec83d26b4ae8, c526937d5e9751a784bb19d40e39ee9a58e87474.

## Testing

I've tested this on my usual corpus of 55,000 JPEG images scraped from the web (11.3 GB).

I have confirmed that all images that successfully decoded in 0.4.11 still decode successfully and identically (bit for bit).

On top of that, 63 images that previously failed to decode now decode successfully.

## Reproducibility

To make sure I have not tampered with the code, you can reproduce my branch with:

```
git checkout add9ba71c9e29665ca65003ead12f85d25d763a7 # the commit on which 0.4.11 was released
git checkout -b zune-jpeg-backport-reproduction
git cherry-pick 1f943d81b1eb189535abfd2afac8f017c57164f3
git cherry-pick efb4cb094a0ba27616c9d4a0909cd7b052e2a72a
git cherry-pick ac18d0bf2a672a8ee57653bbae1c4c2d8fafbba0
git cherry-pick 0938b48b0ed6374a83ba8f80d2e4ec83d26b4ae8
git cherry-pick c526937d5e9751a784bb19d40e39ee9a58e87474
```

Plus manually dropping a temporary test pointing to a local path on your computer (it will show up as a conflict) and bumping the version to 0.4.12

## Publishing

It's best to publish the changes to the git repo too, so I'd recommend this workflow:

```
git clone https://github.com/Shnatsel/zune-image.git zune-image-shnatsel
cd zune-image-shnatsel
git checkout zune-jpeg-4.12
git push git@github.com:etemesi254/zune-image.git # push the branch to your repo for posterity
cd crates/zune-jpeg
cargo publish
```

I hope this will both satisfy the people complaining about decoding failures in `zune-jpeg`, especially users of `image`, and also let you release 0.5.0 at your own pace and without pressure.

Thanks!

**Comment by etemesi254** [comment]
Thank you

will do this probably over the weekend 


just fixing one more bug in https://github.com/etemesi254/zune-image/issues/202#issuecomment-2151108761 (identified the bug, working on the solution)

**Comment by etemesi254** [comment]
The bug has been addressed, could you add https://github.com/etemesi254/zune-image/commit/bdf407db616c5bf56e1646b052badc97fdeeddd4 to the branch for me to do this?

**Comment by Shnatsel** [comment]
Sure! I'll do a test run as well and report results.

**Comment by Shnatsel** [comment]
I've added https://github.com/etemesi254/zune-image/commit/bdf407db616c5bf56e1646b052badc97fdeeddd4 to the branch.

No regressions on my corpus :+1: 

This is good to go!

**Comment by etemesi254** [comment]
https://crates.io/crates/zune-jpeg/0.4.13

Pushed.

Really appreciate this

**Comment by Shnatsel** [comment]
Would you like me to make an announcement about the new release on Reddit?

**Comment by etemesi254** [comment]
Go ahead.
