### ISSUE TITLE
README talks about *minimal* safety?

### ISSUE THREAD

**Issue by jonassmedegaard** [etemesi254/zune-image#220]
I am not a native english speaker, so perhaps I am missing some special twist. It looks odd to me that README.md says that "[s]afety is kept to almost zero in most crates" - shouldn't that be the opposite? Near 100% or that *unsafe* is nearly avoided?

**Comment by etemesi254** [comment]
Sorry, it should be minimal **unsafety**

**Comment by etemesi254** [comment]
Fixed by 4273ce6

Thanks for noticing
