### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by MiniOcean404** [etemesi254/zune-image#223]
I can't solve it myself. I hope you can help me

### Platform
[armv7-unknown-linux-gnueabihf](https://github.com/miniocean404-rust/image-compress/actions/runs/10184256325/job/28171172628#logs)

### Error Info
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/runner/work/image-compress/image-compress/packages/node_modules/.bin:/home/runner/.cache/node/corepack/v1/pnpm/9.6.0/dist/node-gyp-bin:/home/runner/work/image-compress/image-compress/node_modules/.bin:/usr/local/cargo/bin:/opt/hostedtoolcache/zig/0.13.0/x64:/opt/hostedtoolcache/node/20.15.1/x64/bin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" VSLANG="1033" "cc" "-Wl,--version-script=/tmp/rustcj8fmlX/list" "-Wl,--no-undefined-version" "/tmp/rustcj8fmlX/symbols.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.00.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.01.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.02.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.03.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.04.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.05.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.06.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.07.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.08.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.09.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.10.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.11.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.12.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.13.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.14.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.15.rcgu.o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.f378ofwqplwckany0e7c3i0r9.rcgu.o" "-Wl,--as-needed" "-L" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps" "-L" "/home/runner/work/image-compress/image-compress/packages/../target/debug/deps" "-L" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib" "-Wl,-Bstatic" "/home/runner/work/image-compress/image-compress/target/armv7-unknown-linux-gnueabihf/debug/deps/libzune_core-5ceea32f81c0cf4e.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libstd-6e96b02933c46706.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libpanic_unwind-3b6039c203220145.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libobject-cac6ec52dd59f38b.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libmemchr-338bcb43fc5b7a33.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libaddr2line-ec84ce19a99dc14a.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libgimli-4a32e72434f31256.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/librustc_demangle-fbcb5060c3eb8605.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libstd_detect-163afbc8fe3247f8.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libhashbrown-752c0e7e0f2ba6be.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/librustc_std_workspace_alloc-1c841b38ebbd6c9f.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libminiz_oxide-ab2a106a2cf963c5.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libadler-3ef2cb6e8649a8a3.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libunwind-f923286d2eab6750.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libcfg_if-d0f60c22656db634.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/liblibc-7e858a0b28d0822b.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/liballoc-92441624d4e41991.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/librustc_std_workspace_core-83964be755f84e5c.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libcore-c2dec278aa26f83e.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libcompiler_builtins-b240e9bb95c8d274.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib" "-o" "/home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/libzune_jpeg-c8d9d0d381a58561.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /usr/bin/ld: /home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.00.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.00.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/runner/work/image-compress/image-compress/packages/../target/armv7-unknown-linux-gnueabihf/debug/deps/zune_jpeg-c8d9d0d381a58561.zune_jpeg.9dd86eb5fad18007-cgu.00.rcgu.o: relocations in generic ELF (EM: 40)
          

error: could not compile `zune-jpeg` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Internal Error: Build failed with exit code 101
    at ChildProcess.<anonymous> (file:///home/runner/work/image-compress/image-compress/node_modules/.pnpm/@napi-rs+cli@3.0.0-alpha.62_@emnapi+runtime@1.2.0/node_modules/@napi-rs/cli/dist/api/build.js:184:28)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:[531](https://github.com/miniocean404-rust/image-compress/actions/runs/10184256325/job/28171172628#step:12:532):35)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by etemesi254** [comment]
hi, which version are you using, version 0.4.12 had a problem where the lib was set to dylib which may be causing the problem

**Comment by MiniOcean404** [comment]
I'm using zune-jpeg v0.4.13, which is a dependency of image-rs

**Comment by MiniOcean404** [comment]
Can you tell me why it's wrong? I want to learn about it

**Comment by MiniOcean404** [comment]
v0.4.11 also has this problem

**Comment by MiniOcean404** [comment]
By looking at other people's github actions, I found that adding the following configuration can compile successfully.
`
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
`
前提是要安装 `sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf -y`
