### ISSUE TITLE
Python `zil.Image.open()` doesn't work

### ISSUE THREAD

**Issue by kiyoon** [etemesi254/zune-image#231]
I'm using Python 3.10, built zune-python with `maturin develop --release` and a JPEG file straight from a Canon camera.

```python
import zil
im_rust = zil.Image.open("r6.jpg")
```

The above hangs in the recent commit.

b17ed23668954fd4b0e13c19d16d126d501d77c9 is the last commit that works.  
After that commit it fails to compile.  
d09a18bf94ffcca2e74c7f22a224c0134c832c89 is the next commit that compiles that doesn't work.
Until the lastest commit (2582f3d72822d9d855253084f7144cb2e53a327a) it seems to not work at all.

**Comment by etemesi254** [comment]
Fixed by 56833de8156fa3e720a73071877ff60fb0e32d37

It was a circular dependency, image.open called decode_file while decode_file depended on image.open to work.

Thanks for pointing that out

**Comment by kiyoon** [comment]
Thank you!
