### ISSUE TITLE
How to handle faulty jpgs?

### ISSUE THREAD

**Issue by oqpvc** [etemesi254/zune-image#241]
Hi there!
I am trying to deal with JPG files that seem to be faulty, notably for images like the one attached which fails with

`(DecodingError { format: Exact(Jpeg), underlying: Some("Unknown marker 0xFF7F") }`

Other image processing tools like imagemagick can handle the image just fine, and a simple `convert faulty.jpg notfaulty.jpg` fixes the issue, but I am wondering if there is a way I can deal with this type of image directly anyways.

For context, the images are generated by a scanner when scanning to pdf. When I use the pdf crate to iterate over the images and try to use the image crate to make them accessible, I get the error above. Digging deeper, image uses zune to decode the image and when I use zune directly to decode this image, I get the same error, so that's why I'm asking here.

Roughly speaking I'm encountering this error at around 60% of images scanned with that scanner, always with a "Unknown marker 0xFF??" error where the last byte seems random to me.

If you have any idea how I could decode those image straight within rust anyways, that would be greatly appreciated.
![fail](https://github.com/user-attachments/assets/eb1b3a6a-190e-4c7e-8685-277e6b061e15)

**Comment by etemesi254** [comment]
JPEG markers are https://www.disktuna.com/list-of-jpeg-markers/ so 0xff7f is not there, 

Let me investigate will get back to you

**Comment by oqpvc** [comment]
Playing around with this, I realised that the faulty images work fine for me in v0.5.0-rc0.
