### ISSUE TITLE
Infinite loop in zune-inflate on malformed inputs

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#27]
Found by the `decode_buffer` fuzz target. Happens irrespective of #26.

Reproduce with:  `cargo +nightly fuzz run decode_buffer -- -timeout=1s`

Without the `-timeout` argument the fuzzer just hangs and shows 0 executions per second.

**Comment by etemesi254** [comment]
Should be fixed now, sorry my bad.

**Comment by Shnatsel** [comment]
No other issues on this fuzz target after 1 billion executions. Impressive! :+1:
