### ISSUE TITLE
Outdated README and benchmarks on `zune-jpeg` in this repo

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#3]
[The README for zune-jpeg in this repo](https://github.com/etemesi254/zune-image/tree/main/zune-jpeg#readme) still mentions multi-threading, but I understand it is no longer used. It would be nice to update the README and benchmarks.

**Comment by Shnatsel** [comment]
> For more up-to-date benchmarks, see [Benches.md](https://github.com/etemesi254/zune-image/blob/main/Benches.md).

That link is a 404, but it's understandable if you don't want to fill in the benchmarks at this time.

**Comment by etemesi254** [comment]
Works now.

https://github.com/etemesi254/zune-image/blob/main/zune-jpeg/Benches.md

**Comment by Shnatsel** [comment]
Thanks! The benchmarks look great! :tada:
