### ISSUE TITLE
Provide a dedicated DecodeError variant for exceeding the size limit

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#31]
Right now it's impossible to distinguish the error caused by exceeding the size limit from other errors. It should be its own dedicated enum variant.

This can be important for showing user-friendly messages, such as "Use the --size argument to increase the limit" in a command-line tool.

**Comment by Shnatsel** [comment]
This is about `zune-inflate`. Sorry I didn't mention it in the original message.

**Comment by etemesi254** [comment]
Done. in a quite long commit

Also added gzip decoding while at it see e965293db7400ad4cb1ebe1c72398de12a2d2b15
