### ISSUE TITLE
zune-inflate: return the resulting Vec on failure

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#33]
Streaming decompressors like `flate2` usually write to a caller-provided buffer, so they write out _some_ data on failure, and it's possible to recover part of the data even if decompression fails.

Even the methods that write to a `Vec` in `miniz_oxide` return the Vec they've written so far on failure, using [their custom error struct](https://docs.rs/miniz_oxide/0.6.2/miniz_oxide/inflate/struct.DecompressError.html).

It would be nice to have a similar mechanism in `zune-inflate`. I don't actually have use cases for this, but it seems like an easy thing to do.

**Comment by etemesi254** [comment]
Added now.
