### ISSUE TITLE
Enum variants should not be added/removed based on features

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#34]
https://github.com/etemesi254/zune-image/blob/a54cd92a3e5b3a51c38a76a04ad431189a901df8/zune-image/src/errors.rs#L12-L21

This code may break some valid uses because Cargo features are additive.

Imagine you wrote a library that only decodes JPEG images. You can write the following matching code:

```rust
match error {
    // .. all variants shared between formats here ..
    JpegDecodeErrors(err) => eprintln!("Failed to decode JPEG: {err}");
```

However, if some user of your library also depends on another library that works with PNG images via `zune-image`, the required features for both libraries get merged. This causes the `PngDecodeErrors` variant to appear and break compilation for the library processing JPEG, because there is now an unhandled enum variant.

A quick and easy fix to prevent this kind of breakage is making the enum `#[non_exhaustive]` so that the caller always has to include a catch-all clause ` _ => eprintln!("Unknown error")`. This also lets you add formats easily. It is however a little cumbersome to use for the caller.

A better way would be converting all format into an error type provided by `zune-image`, such as `FormatError`, instead of exposing the error types from format crates in the public API of `zune-image` crate.

**Comment by etemesi254** [comment]
Makes sense, but this removes the recoverability of some image errors.

**Comment by Shnatsel** [comment]
Well, you could have several enum variants for recoverable and unrecoverable errors. Or have as many variants with as many details as you please - the only restriction is that they should not come from a crate that is included in the build only when certain features are enabled.

**Comment by etemesi254** [comment]
I prefer the second alternative, one can't have the whole cake and eat it sadly

**Comment by Shnatsel** [comment]
FWIW if there are per-format enum variants, then adding a new format is a semver-breaking change, unless the enum is marked `#[non_exhaustive]`.
