### ISSUE TITLE
Some images garbled after JPEG to PPM conversion

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#4]
Running `zune --input Pithecophaga_jefferyi.jpg --out out.ppm` garbles the image.

Original:

![Pithecophaga_jefferyi](https://user-images.githubusercontent.com/291257/202910690-9d18be99-16b1-4b20-b8cb-8bf4a0d1542e.jpg)

Result:

![out](https://user-images.githubusercontent.com/291257/202910720-986c769a-fd9c-4aa8-b97b-32fbf88482f3.png)

The image is [sourced from wikimedia.](https://commons.wikimedia.org/wiki/Pithecophaga_jefferyi#/media/File:Pithecophaga_jefferyi.jpg)

**Comment by etemesi254** [comment]
On it

**Comment by Shnatsel** [comment]
I'm getting similar issues on many images, so I'm going to hold off further testing until this is fixed. Another sample:

![kotenok_gaff_cat_tay_198](https://user-images.githubusercontent.com/291257/202917956-da134a90-27d9-4f55-b24a-5531edb4e67f.jpg)

decoded like this

![out](https://user-images.githubusercontent.com/291257/202917963-20905e8a-7d89-48f5-822b-07332a9c251f.png)

**Comment by etemesi254** [comment]
Hi, could I get more samples of such corrupted images,

Esp the second one, first one is fixed

**Comment by Shnatsel** [comment]
Now I'm getting this error on all images:

`ERROR [zune_bin]  Could not complete workflow, reason Data length does not match image dimensions`

I'm running `zune --input in.jpg --out out.ppm` on commit 8f92e8be211eb9a81b37aa57f5864cdac189ba4a

**Comment by Shnatsel** [comment]
FWIW, PPM to PPM conversion also fails with the same message.

I won't be able to conduct any tests until the `Data length does not match image dimensions` issue is fixed.
