### ISSUE TITLE
Inflate: `copy_rep_matches` can be faster

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#41]
This is a very hot function responsible for 30% of the time spent in inflate on an `exr` crate benchmark:

https://github.com/etemesi254/zune-image/blob/5097f4c921c8982576690ecb77bebace383ca9c9/zune-inflate/src/utils.rs#L93-L102

There are at least two ways to speed it up:

1. https://crates.io/crates/rle-decode-fast implements an algorithm copying data in batches exponentially increasing in size rather than byte-by-byte. This should be faster than the current approach, although may need some tweaking (e.g. capping the exponent at some size - needs benchmarks). Disclaimer - I took part in developing that, I may be biased.
2. Nothing is done to eliminate bounds checks. I don't think using an iterator will work here, but there's ample room for optimizer hints. I've [successfully applied those in the `inflate` crate](https://github.com/image-rs/inflate/pull/43) for this very algorithm.

**Comment by etemesi254** [comment]
Isn't the first one unsafe?

It does the equivalent of the below C code

```c
while (dst<src){
   *dst++ =*src++;
}
```

And what exact optimizer hints? Would love to explore them.
Lemme experiment with some few ideas and see how it turns out

**Comment by Shnatsel** [comment]
`rle-decode-fast` crate impements RLE in safe code. It includes some unsafe for a function that was since included in the standard library, `vec.extend_from_within()`, but the RLE code itself is safe.

And no, it doesn't do what you described - it copies regions that are exponentially increasing in size instead of copying byte-by-byte:

https://github.com/WanzenBug/rle-decode-helper/blob/bdafaedc43accc2c7c53408144f2bc58bfc1bb0a/src/lib.rs#L35-L65

Same result, different and faster implementation.

> And what exact optimizer hints? Would love to explore them.

I meant the bounds check elision tricks I covered in the article. Adding `assert!`s on slice lengths allowed the optimizer to remove bounds checks in this function in the `inflate` crate, see https://github.com/image-rs/inflate/pull/43

**Comment by etemesi254** [comment]
Assert hints are finicky, they are amazing when they work but they don't work mostly

e.g say `assert(offset+12<dest.len())`; won't  help remove bounds check, because offset may be a big integer and adding 12 in release mode causes it to wrap around and become smaller than `dest.len()`, meaning that passes but during indexing it's an out of bounds. 
The compiler knows this and hence it can't elide it.

Theoretically saturating add should work but it also doesn't, this is probably a missed optimization.

I've done a small change in the dev branch, should reduce the number of times we call copy_rep_matches, I've tested on my machine that fuzzing still works, and all tests pass.

Could you check if that helps

**Comment by Shnatsel** [comment]
Sadly my machine is very noisy and is not really usable for benchmarking. I could get a cloud VM for the tests, but you'll need to tell me what I'm looking for exactly - criterion benchmark times or something else? The generated assembly, maybe?

**Comment by Shnatsel** [comment]
Anyway I'm probably off for the night, but I'll try to take a look tomorrow or so.

**Comment by etemesi254** [comment]
just Criterion Benchmarks, or whatever you used for exr checks, hopefully the region should be smaller.

**Comment by Shnatsel** [comment]
`$ cargo +nightly fuzz run decode_buffer -- -timeout=1s`

Almost immediately prints:

```
thread '<unnamed>' panicked at 'assertion failed: self.bits_left >= num_bits', /home/shnatsel/Code/zune-image/zune-inflate/src/bitstream.rs:106:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Also I think `exr` tests hang. PR: https://github.com/johannesvollmer/exrs/pull/179 but the `decode_buffer` fuzzer should find it too

**Comment by etemesi254** [comment]
Fixed in 0.2.3

**Comment by etemesi254** [comment]
> just Criterion Benchmarks, or whatever you used for exr checks, hopefully the region should be smaller.

The check that was added makes us call `copy_rep_matches` for matches less than `FASTCOPY_BYTES` and whose offsets would cause overlap on the current source.

Previously as long as the match was an  overlap, we would call `copy_rep_matches`.

This now means for the hot loop, copy_rep_matches is called only for situations where loop is less than 16, remember we have room to do sloppy copies, but I can't get the compiler to elide bounds check even with a fixed/constant and asserts

**Comment by etemesi254** [comment]
THere is a faster rep copy algorithm with this commit https://github.com/etemesi254/zune-image/pull/45/commits/6bb95ace8c6f46db3a6ea9e1d86347c3442235d6 I think it should boost the speeeds currently.

Fuzz tested the three fuzzers this time,(sorry for the 0.2 release), so I don't think there are mistakes, but additional fuzzing wouldn't hurt.

CI should run fuzzing now.

**Comment by Shnatsel** [comment]
I confirm it has improved the `exr` benchmark. Before:

```
test read_single_image_non_parallel_zips_rgba        ... bench: 199,622,716 ns/iter (+/- 338,823)
```

After:

```
test read_single_image_non_parallel_zips_rgba        ... bench: 187,659,328 ns/iter (+/- 76,902)
```

miniz_oxide for comparison:
```
test read_single_image_non_parallel_zips_rgba        ... bench: 196,783,469 ns/iter (+/- 172,721)
```

**Comment by Shnatsel** [comment]
> sorry for the 0.2 release

No worries. Nobody's using it in prod yet, and it's good that we broke something now and learned from it rather than later!

**Comment by Shnatsel** [comment]
I see that in https://github.com/etemesi254/zune-image/commit/6bb95ace8c6f46db3a6ea9e1d86347c3442235d6 the copying loop is still [very hot](https://user-images.githubusercontent.com/291257/210165142-f8a62cf1-3343-4f4c-b62d-c93cb6bb4b57.png). I have an idea on how this could be improved, and how to remove bounds checks here.

We can write the output without bounds checks by iterating over the output slice with `chunks_exact_mut` as long as we have somewhere to copy from that doesn't overlap with the place to which we're writing.

imagine we have the fragment `abc` which we need to RLE-decode into `abc.abc.abc.a` (dots inserted for readability only, don't appear in the output).

The possible permutations we may have to write, assuming we copy 4 bytes at a time (`FASTCOPY_BYTES` = 4), are: `abca`, `bcab`, `cabc`, and that's it. So as long as we have written a slice that contains all of them, namely `abc.abc`, we can do `split_at_mut` on the stream, have the `abc.abc` on the left side, iterate over `chunks_exact_mut` on the right side, and copy the `abca`  `bcab` `cabc` chunks from the left to the right.

This is guaranteed to remove the bounds checks from the hot loop.

We need to do one final copy of the remainder afterwards for correctness, as is common for `chunks_exact_mut`, to process any remaining data less than `FASTCOPY_BYTES`, but that's not hard.

**Comment by etemesi254** [comment]
> I confirm it has improved the `exr` benchmark. Before:
> 
> ```
> test read_single_image_non_parallel_zips_rgba        ... bench: 199,622,716 ns/iter (+/- 338,823)
> ```
> 
> After:
> 
> ```
> test read_single_image_non_parallel_zips_rgba        ... bench: 187,659,328 ns/iter (+/- 76,902)
> ```
> 
> miniz_oxide for comparison:
> 
> ```
> test read_single_image_non_parallel_zips_rgba        ... bench: 196,783,469 ns/iter (+/- 172,721)
> ```

This does also improve png decoding by 3% , almost hitting 2x faster speeds than imagers/png

**Comment by etemesi254** [comment]
Permute copy is interesting, the only decompressor I'm aware that does this is snappy, at https://github.com/google/snappy/blob/984b191f0fefdeb17050b42a90b7625999c13b8d/snappy.cc#L218-L339,  but do remember the loop is copying less than FASTCOPY_BYTES(16 for now). this may mean we should not spend more time setting it up than we spend copying.

**Comment by Shnatsel** [comment]
Ah, that's fair. 

I wonder if permute copy with a really small size, like 2, will help at all? It will eliminate bounds checks on the actual copies, but may have other drawbacks.

**Comment by Shnatsel** [comment]
Chances are good that the cost of the setup is going to dominate. It might be useful for non-overlapping copies though, since those are also hot and also have bounds checks right now.

**Comment by etemesi254** [comment]
I did some benchmarks with libdeflate, that thing is wickedly fast.

zune-inflate: 169 m
miniz-oxide: 174 m
libdeflate: 148 m

I think that warrants some more agressive safe optimizations. Lemme extract that zlib file from the exr file

**Comment by Shnatsel** [comment]
Oh, the setup for permute copy is actually quite cheap: the sequence only needs to occur twice in a row (i.e. be copied once), after which you can run permute copy for the rest. 

So it is an improvement as long as the sequence we're repeating is short; but if the sequence is as long or longer as the chunk we're writing, then we'll just spend the entire time in the setup and never reach permute copy.

**Comment by Shnatsel** [comment]
Sorry if I'm stating the obvious, I'm discovering things and thinking them through as I go :sweat_smile:

**Comment by etemesi254** [comment]
```rust
current_position += FASTCOPY_BYTES;
  
let count = (length - 1) / FASTCOPY_BYTES;

 for (src_chunk, dest_chunk) in src[dest_src_offset..]
      .chunks_exact(FASTCOPY_BYTES)
      .zip(dest.chunks_exact_mut(FASTCOPY_BYTES))
      .take(count)
  {
      dest_chunk.copy_from_slice(src_chunk);
  }
```

Would have been brilliant for the long copy, but doesn't work when the match becomes overlapping

**Comment by Shnatsel** [comment]
The long copy is hot on the profile too, so if this works for it - amazing!

I think you'll need to do a permute copy for correctness, so use slightly more complex iterator on `src`, something like `src.windows()`.repeat()` with maybe even a `step_by()` in there somewhere, not sure.

But I'm going to take a break from thinking about optimizing RLE, it has kind of consumed my life lately :sweat_smile:

**Comment by etemesi254** [comment]
> Sorry if I'm stating the obvious, I'm discovering things and thinking them through as I go sweat_smile

Ideas are always welcome here :)

**Comment by etemesi254** [comment]
> The long copy is hot on the profile too, so if this works for it - amazing!
> 
> I think you'll need to do a permute copy for correctness, so use slightly more complex iterator on `src`, something like `src.windows()`.repeat()`with maybe even a`step_by()` in there somewhere, not sure.
> 
> But I'm going to take a break from thinking about optimizing RLE, it has kind of consumed my life lately sweat_smile

I took my break,time to put my skills to test :)

**Comment by Shnatsel** [comment]
There have been RLE decoding speed improvements and this issue isn't actionable anymore, closing.
