### ISSUE TITLE
`zune-inflate` fails to roundtrip in v0.2.0 release from crates.io

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#42]
I've tried to add `zune-inflate` to the `exr` crate, and tests failed. I've re-run the `roundtrip` fuzz target and it immediately found inputs that failed to roundtrip.

Fortunately there aren't any production users yet, so nothing is broken by this.

I suggest running fuzzing for a small number of iterations on CI to make sure this doesn't happen again.

**Comment by Shnatsel** [comment]
The CI command could look something like this: `cargo fuzz run roundtrip -- -runs=1000000 -timeout=1s`

Needs a nightly compiler.

**Comment by etemesi254** [comment]
A fix just landed at v 0.2.1

Doing the CI thing now

**Comment by etemesi254** [comment]
Added CI, closing this
