### ISSUE TITLE
Inflate: not faster than `miniz_oxide` on exr benchmark

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#46]
```
git clone https://github.com/Shnatsel/exrs
cd exrs
git checkout zune-inflate
cargo bench read_single_image_non_parallel_zips_rgba
```

The Cargo.toml file is locked in to 0.2.1. Edit it to point to 0.2.2 and you'll see a performance regression, to the point that `miniz_oxide` used on the `master` branch becomes slightly faster than `zune-inflate`.

This is not reflected in the zune-inflate benchmark, so apparently it represents significantly different data patterns.

**Edit:** actually 0.2.1 doesn't pass tests, you have to upgrade to 0.2.2 for correctness.

**Comment by Shnatsel** [comment]
Improved by #41

**Comment by Shnatsel** [comment]
Half the time here is spent in various parts of RLE decoding, so closing in favor of https://github.com/etemesi254/zune-image/issues/41

**Comment by etemesi254** [comment]
Looking into it

**Comment by Shnatsel** [comment]
If you profile the benchmark with Samply (either on Linux or on Mac) you can double-click the items in the flame graph to view the source code, and where the time is spent within the function line by line. I've found it helpful to understand where time is spent.

This only works while Samply is running, this won't work in profiles shared on the web. That's how I got [this image](https://user-images.githubusercontent.com/291257/210165142-f8a62cf1-3343-4f4c-b62d-c93cb6bb4b57.png).

**Comment by etemesi254** [comment]
I didn't know about samply.

Thanks for that, 

was wondering how you actually got those values

**Comment by Shnatsel** [comment]
I've updated the article about bounds checks with instructions for using Samply on Linux.
