### ISSUE TITLE
16-bit PNG images are cut off when decoding

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#52]
Original:

 ![69](https://user-images.githubusercontent.com/291257/211037914-79507608-7359-4037-b8c1-ee4fb55c1a5c.png)

Zune converted to PPM and then with imagemagick to PNG:

![69 png ppm zune](https://user-images.githubusercontent.com/291257/211037985-22d80cf3-8288-4ec0-a3e3-4412b4bcf041.png)

Original:

![failed-repos](https://user-images.githubusercontent.com/291257/211038287-d1312498-273e-4669-83be-cd20a331a6da.png)

Zune:

![failed-repos png ppm zune](https://user-images.githubusercontent.com/291257/211038308-a89fe400-4ff7-4dd5-896f-2e2acd5bfa65.png)

Tested on commits dfb7ddd and 74c36b8aba79ebde04fd43ddd92afb73198c9d5b

**Comment by etemesi254** [comment]
Hi , could you test using gimp save as 16 bit and then try to decode via zune-png

Might be that images say they're 16 bit and are encoded as 8 bit.

**Comment by Shnatsel** [comment]
GIMP loads this as a 16-bit image, and after saving from GIMP and converting with zune the issue persists.

**Comment by etemesi254** [comment]
As usual, would love you to confirm if the issue is no longer present.

Also development switched to `dev` branch.

**Comment by Shnatsel** [comment]
I can confirm this is fixed.
