### ISSUE TITLE
PNG: some images are too bright

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#54]
Original:
![14584](https://user-images.githubusercontent.com/291257/211042435-2e0699e9-c89c-424f-ba72-243370fdfea3.png)
Zune:
![14584 png ppm zune](https://user-images.githubusercontent.com/291257/211042436-baeac6fc-7252-4a5e-9225-7c3e2035b986.png)
Original:
![449554](https://user-images.githubusercontent.com/291257/211042439-9ce9c503-0f21-4a6f-971f-fd649a3c51d6.png)
Zune:
![449554 png ppm zune](https://user-images.githubusercontent.com/291257/211042441-da95c3e5-d491-4bc6-9bb1-537a97de85f3.png)

Tested on commit 74c36b8aba79ebde04fd43ddd92afb73198c9d5b

**Comment by Shnatsel** [comment]
Potentially relevant discussion about gamma: https://github.com/etemesi254/zune-image/issues/51#issuecomment-1373728674

**Comment by etemesi254** [comment]
Hi

Do they have a gama chunk

Also gama correct is put as an option, in png/src/options.rs could you try setting gama correct to false(line 56 )

Also I'm a bit far away from my dev machine so these will be addressed from next week if they are an issue, but feel free to report any more that you find

**Comment by Shnatsel** [comment]
I actually have lots of images that are too bright. These are just two examples.

Disabling gamma correction does get these images back to normal, yes. Not sure if that's because nothing else performs gamma correction, or because this gamma value would result in an equivalent image in other decoders but not in zune.

**Comment by etemesi254** [comment]
Spng supports gama correction as a flag I think the best way to test this may be to have it load it apply gamma correction and then quit.

But I'm starting to think that it's better off left as an opt in than an opt out

**Comment by etemesi254** [comment]
I thought about it and finally figured it out.

Gamma correction should be done later when needed


I should have an image attribute that stores whether the image is linear or gamma corrected
using an enum (,two fields, Linear,sRGB )

Gamna correction should occur in zune-image and not in zune-png

Gamma correction should occur for things that will do addition and subtraction (brighten, etc) on pixels
and blending operations when they are implemented.

Images in linear should be encoded back to sRGB colorspaces before encoding

So this is a bug

Will fix it in future iterations

**Comment by etemesi254** [comment]
Fixed in the dev branch as of 209d3ce55a75cdcf6d27ba25d6737a5e7857e974
