### ISSUE TITLE
PNG: "Bit depth of 2 only allows Greyscale or Indexed color types, but found Palette"

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#57]
```
ERROR [zune_png::headers] Bit depth of 1 only allows Greyscale or Indexed color types, but found Palette
```

Happens for bit depths of 1, 2 and 4.

But the spec clearly states that the valid bit depths for palettle type images are 1, 2, 4 and 8: http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html

**Comment by Shnatsel** [comment]
And yes, this causes issues for real-world images. Example: 
![dome_mono](https://user-images.githubusercontent.com/291257/212582067-90eae027-0908-4ae8-aec3-2d6dd12b511e.png)

**Comment by etemesi254** [comment]
Yes, this is an error.

Will close this once I fix palette decoding for png

**Comment by etemesi254** [comment]
FYI, the spec says a paletted image cannot be in color types 0 and 4.

Those color types are  Luma/Grayscale  and Luma+Alpha. Hence the error message displayed.

So images with such are not spec compliant

**Comment by etemesi254** [comment]
Fixed in the latest dev branch
