### ISSUE TITLE
PNG: Grayscale+Alpha images converted to just Grayscale in PPM

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#58]
Not sure if this is actually a bug, but it showed up in my search for divergences from imagemagick.

This file:

![hi22-action-music-cross](https://user-images.githubusercontent.com/291257/212581513-9e8890c6-69e3-4d05-a1e8-00b2471e3b2b.png)

Gets a white background instead of a transparent one when converting to PPM with the `zune` command-line tool:

![hi22-action-music-cross png ppm zune](https://user-images.githubusercontent.com/291257/212581610-b7c560ff-875c-44d8-b407-850d4fa6fa6e.png)

**Comment by etemesi254** [comment]
Fixed.
Was an issue with handling tRNS chunk with specified bit depth.

FYI: png handles this wrongly too, it doesn't expand pixels with tRNS chunk and reports this as grayscale, and not grayscale+alpha.

Same as libspng rust port, but the C code has support for this, so I'm not sure what's going on with the port(or it might be me)
