### ISSUE TITLE
PNG: some valid images fail to decode

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#60]
Tested on commit 4e74f01af7a29e74f5ca83dbaa85e816839d2c1d 

Images that fail to decode: [zune-png-failures.tar.gz](https://github.com/etemesi254/zune-image/files/10503323/zune-png-failures.tar.gz)

I can't guarantee all of them are supposed to be decodable - some may have been generated by a fuzzer.

**Comment by etemesi254** [comment]
Most should be fixed by 31899d89c26885bf04162076545857dd003589ba,  the ones that aren't are too short or have mismatched CRC chunks.

**Comment by Shnatsel** [comment]
Great!

Ignoring CRC and trying to decode anyway is probably good default behavior for the command-line tool to try and recover slightly corrupt images. This is something you might want to flip in the CLI tool.
