### ISSUE TITLE
JPEG: red channel shifted by 1 pixel

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#64]
It seems that in the images decoded by zune-jpeg, the red channel is shifted by 1 pixel along the vertical axis. 

We've seen this kind of failure mode in small images of flags before, but manebooru has an image that makes it very obvious:

[16006511942024190319402](https://user-images.githubusercontent.com/291257/215272345-4f9e9fef-c261-4d73-adcb-0f1ab7b218ef.jpg)

If you decode this with `zune-jpeg` and switch between the original and the zune decoded image, you'll clearly see the reds move.

Tested on commit 48757e36f9a39df01ddb28fc353d00547a9bd68e

**Comment by Shnatsel** [comment]
And that's the final remaining issue. Once #63 and this are done, we're good to go!

**Comment by etemesi254** [comment]
Was this the only image in that corpus with such characteristic?

**Comment by Shnatsel** [comment]
No, this is very common. There are many images like these, this one just has it the most pronounced on the overall similarity metric.

Here's another, must smaller one: [cs_CZ](https://user-images.githubusercontent.com/291257/215338002-d08c0de6-0c94-4d76-a0f1-5010d7b1829b.jpg)

And another one with the easily noticeable difference: [seal](https://user-images.githubusercontent.com/291257/215338122-b5de8749-f764-454b-8706-34f1b2b056d4.jpg)

**Comment by Shnatsel** [comment]
I've found a PNG exhibiting the same issue: [2015 01 14_lp_001](https://user-images.githubusercontent.com/291257/215356465-73da83bd-879b-4085-9de0-2ca8edb85135.png)

So the problem might be not in any particular decoder, but in some shared component or the PPM encoder.

**Comment by etemesi254** [comment]
Figured it out


It's a long bug


Will fix it over the weekend

**Comment by etemesi254** [comment]
Could you kindly run the decoder for your corpus.
 
 The reason was that I initially fixed this the not so complicated way,which required a big alloc which significantly slowed down decode speed (from 100 ms to 170 ms), so I had to do it the complicated way or (https://github.com/etemesi254/zune-image/blob/f7ffb8a939c4ca18163dc40a209acab6ed7b5b6b/zune-jpeg/src/worker.rs#L329-L516)
 
 I'd like to see if it holds water, on my side I think it works, running with convert on the attached `seal.jpg` reports
 
 ```
RMSE 508.24 (0.00775524) ./seal.jpg
Absolute error count 78299./seal.jpg
DSSIM  0.000547915 ./seal.jpg
PSNR 42.2081 (0.422081) ./seal.jpg

 ```
 
 And there is no visual difference when viewing with two editors

**Comment by Shnatsel** [comment]
I'll test this later today. Thanks a lot for the fix!

**Comment by Shnatsel** [comment]
Preliminary result: the top Manebooru mismatches are fixed and have very low divergence now. So this looks promising. I'll update you once the run on my entire corpus completes.

**Comment by Shnatsel** [comment]
Yep, no more divergences on my corpus. Excellent!
