### ISSUE TITLE
`--resize` garbles images

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#66]
Original:

![tmpfqupp1o9](https://user-images.githubusercontent.com/291257/215279572-6562d2e5-8114-4acd-ae1a-69e7a16cd3c4.png)

After `zune --resize 200x200 --input tmpfqupp1o9.png --output doggo_thumb.ppm`

![doggo_thumb](https://user-images.githubusercontent.com/291257/215279590-3029e2d8-af4b-4a20-b201-0274b46a0f2f.png)

This image was generated by me using Stable Diffusion, so I can license it as permissively as you like.

Happens on both PNG and JPEG, so I don't think the issue is tied to a particular format.

Tested on commit 48757e36f9a39df01ddb28fc353d00547a9bd68e

**Comment by etemesi254** [comment]
Yes, resize anb blurs have some work needed to make them right which I've been putting in the back burner for long, after finishing jpeg and png decoding, this was the next thing to fix.

**Comment by etemesi254** [comment]
😅 d84b582b984f4fe9dd9bd96c8af5ed4cb4c01e3c

But it's bilinear resize, fast but not that good quality wise.
Will implement others in coming weeks

**Comment by Shnatsel** [comment]
Yeah it's probably best to take things one at a time
