### ISSUE TITLE
JPEG fails to decode a valid image: "No more bytes"

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#67]
The attached image fails to decode with `zune` as of commit f749f95aa881d14d1123ebe24bed1232acdccf73

`ERROR [zune_bin]  Could not complete workflow, reason jpg: "No more bytes"`

[1601903733902076022688216](https://user-images.githubusercontent.com/291257/215337280-2a428d88-e353-4c00-9162-37c65452f2a4.jpg)

**Comment by Shnatsel** [comment]
There are only 2 of these among a dataset of 300,000 images.

**Comment by etemesi254** [comment]
It has  a premature end , `djpeg` also notes this.

**Comment by etemesi254** [comment]
We now print a warning instead of error in case decoder is not in strict mode (default for cmd)
