### ISSUE TITLE
Panic on out-of-bounds access when resizing some images

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#68]
Resizing the following image causes a panic:  [gender-select](https://user-images.githubusercontent.com/291257/215348989-996d4180-a5cc-435c-b735-c04da7d53154.png)

```
thread 'main' panicked at 'index out of bounds: the len is 146432 but the index is 146432', zune-image/zune-imageprocs/src/resize/bilinear.rs:48:31
```

This is a screenshot from the game [Shadowkey](https://en.wikipedia.org/wiki/The_Elder_Scrolls_Travels:_Shadowkey)

Command: `zune --yes --resize 200x100 --input "gender-select.png" --out "thumb.ppm"`

Tested on commit e794b64a5874e5ff58c871aec8cf5290eee81203

**Comment by etemesi254** [comment]
I've removed the whole thing.

Needa a lot more work in order to handle things like colorspaces and alpha channels.

When it's done i'll close this and the other issue pertaining to resize

**Comment by Shnatsel** [comment]
Since these are not active issues I'll go ahead and close them. They will still be archived here if/when you decide to resurrect the code.
