### ISSUE TITLE
PNG: don't verify adler32

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#71]
A PNG file contains two checksums:

1. Adler32 describing the checksum of the decompressed ZIP data
2. CRC32 describing the checksum of the compressed file

Adler32 is slower than crc32 (which has a dedicated instruction to compute it on x86).

adler32 allows verification of the final uncompressed bitstream; however, the input file integrity is already verified by crc32 in the PNG format. This makes adler32 verification redundant, since the only things it can detect are:

1. A bug in the zlib decompression implementation
1. File corruption so subtle that the outer crc32 missed it

Both of these scenarios are so rare that they're not worth the extra runtime overhead in the default configuration.

Disclaimer: my understanding is based on the summary provided [here](https://stackoverflow.com/questions/33914640/adler-32-checksums-in-a-png-file), I'm not an expert on the PNG format.

**Comment by etemesi254** [comment]
My thoughts are

1. Crc has a dedicated instruction on x86 and even arm, but Intel x86 decided to use  a different polynomial than what gzip,png needs see Wikipedia article on  [crc32](https://en.wikipedia.org/wiki/Cyclic_redundancy_check) and the sextion specifically with the title Polynomial representations of cyclic redundancy checks

So the instructions can't be used for our use case.


2. You can do simd crc32 by a technique called carryless multiplication, can't find an article to link to sadly.


3.  The spec says that adler is used as a cross check of a correct deflate implementation at https://www.w3.org/TR/png/#10CompressionCM0

So I have no problem turning it off.


Generally I would like to have it as a tunable option and it should be in core as a field

For this and other quirks, I'd prefer to use bitflags (with the bitflags crate) to allow turning such things on and off and have defaults like this turned off

**Comment by Shnatsel** [comment]
> Generally I would like to have it as a tunable option and it should be in core as a field

Yeah, that makes perfect sense.

> For this and other quirks, I'd prefer to use bitflags (with the bitflags crate)

I don't think bitflags are relevant these days except for syscalls or situations where you have the same struct repeated lots of times. I'm pretty sure if you just use bools in a struct instead of bitflags, the benchmark numbers will be the same, and it will be simpler to use. The builder pattern can be used to conveniently construct these structs.

**Comment by Shnatsel** [comment]
Hmm, are you sure the polynomial is an issue? 

The `png` crate uses the [`crc32fast`](https://crates.io/crates/crc32fast) crate for crc32. They [don't seem to be doing anything to set a custom polynomial](https://github.com/image-rs/image-png/blob/6862566bf42685c461b24ae2963e127b9de2df2a/src/decoder/stream.rs#L10). And that crate advertises use of the `pclmulqdq` instruction.

I've just encoded a PNG file with `image` and the crc32 is OK according to `pngcheck`.

**Comment by etemesi254** [comment]
`crc32fast` already says it's using the `crc-32` variant which is used by png,gzip, ethernet etc.

Intel have an arch specific instruction for [`crc32`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=crc32&ig_expand=1561) which uses `CRC-32C (Castagnoli)`,  
which are fundamentally incompatible.

If they weren't the  `crc32fast` crate would be using `_mm_crc32_u32/u64` instead of whatever carryless multiplication techniques they implement.

The implementation of polynomial setting is found in [crc](https://docs.rs/crc/3.0.1/crc/) crate

When you asked about the dedicated instruction, I assumed you meant `_mm_crc32_u32/64`

**Comment by Shnatsel** [comment]
Done in 71a1f56360d2e1389a939e5306f35119a157d196, closing.

**Comment by etemesi254** [comment]
>My issue with bitflags is that the option combinations are not at all readable. For example, currently doesn't enable unsafe optimizations even though the documentation says it does:



Question, won't this lead to a big  struct when we start adding quirks for other formats?

**Comment by Shnatsel** [comment]
It might. But I understand it is accessed relatively rarely, and if the size becomes a problem we can just pass it by reference.

If the bitflags are exposed in the public API, we might eventually run out and have to make an API break to add more flags.

You could also compact the data by storing the highest optimization level enabled (e.g. USE_SSE3 implies USE_SSE2) as opposed to bools.
