### ISSUE TITLE
Adler32 mismatch - potential bug in `zune-inflate`?

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#72]
The following image has valid CRC32, but `zune` complains that the decompressed result doesn't match the embedded adler32.

Since Adler32 in gzip applies to the decompressed data, This means one of three things:

1. the image is damaged in such a way that avoids detection by crc32
1. zune-inflate decompresses this stream incorrectly
1. adler32 is calculated incorrectly by zune

[1443708892 angelfonds_1443660918 crazybear_05ccadee-c566-4e25-9046-f4a437530a2d](https://user-images.githubusercontent.com/291257/215902901-8234f38e-fe29-4093-88ab-67b175426bf7.png)

Tested on commit 37163f128de78d6630ae7312cc63fa9f6f6dfef0

**Comment by etemesi254** [comment]
`pngfix` reports an error on zlib chunk.

Disabling Adler check makes it work.

This one in a lot of images is probably the reason adler + crc chunk exists

**Comment by etemesi254** [comment]
Disabled by default.

Enabling `--strict` mode in command line returns the error(in strict mode the decoder is more standards compliant)
