### ISSUE TITLE
Some images appear blank after PNG > PPM > imagemagick PNG conversion

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#73]
These images become fully transparent after conversion to PPM with `zune` and then to PNG using `convert`:
[zune-image-png-37163f128-blank.tar.gz](https://github.com/etemesi254/zune-image/files/10551170/zune-image-png-37163f128-blank.tar.gz)

Is that an issue with `zune-image` or `convert`? Perhaps `zune` is using some advanced PPM features that `imagemagick` can't handle?

Tested on `zune-image` commit 37163f128de78d6630ae7312cc63fa9f6f6dfef0

**Comment by etemesi254** [comment]
My bad, I thought fixing one meant all were fixed
