### ISSUE TITLE
Shifted rows and other issues on multiple JPEG images

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#8]
This is similar to #7, but occurs even after the fix for it. Same testing methodology and corpus as in #7.

Images with the largest mismatch compared to the expected behavior:  https://mega.nz/file/k0V3CJTI#OPJMkK7ezkrsVN_qHgTvD2qf4RsNmpfRBF6L_7oZdrA

Tested on commit b22c7e0d7e5e97717795a51dc95ffe19462d9294

Some images have an issue with shifted rows similar to #7, but there are also other issues, e.g. this image:

![mountain lion 1](https://user-images.githubusercontent.com/291257/203638630-301f3017-aa67-4506-bd67-9d9a80ef3ac3.jpg)

Which gets decoded like this:

![mountain lion 1 jpg](https://user-images.githubusercontent.com/291257/203638674-e8223167-217f-4db9-b6ef-68a74363c127.png)

Although it has some corrupted bands so it may very well be out of scope. RST markers are supposed to make decoding robust against this kind of corruption, however.

**Comment by etemesi254** [comment]
Sorry for late reply, will look for them in the weekend.

**Comment by Shnatsel** [comment]
No need to apologize, please take your time!

Judging by my experience with other decoders, I'll keep these reports coming for a while yet. It's easy to get burned out if you rush to fix every one of these. I really mean it when I say you shouldn't hurry to fix these.

**Comment by etemesi254** [comment]
Second one is fixed.

The first one still investigating.

Might take a while

**Comment by etemesi254** [comment]
Came up with a pretty neat solution, sorry it took long, didn't want an ad-hoc solution.

Feel free to test and report if any more errors crop up
If none please close the issue

**Comment by etemesi254** [comment]
closing this, confirmed most of them are working.

**Comment by Shnatsel** [comment]
I don't mind the wait. I'd rather have a proper solution than a quick one!
