### ISSUE TITLE
Using `mmap()` without additional locking is unsound

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#82]
`mmap()` can only be used safely when the file is *guaranteed* not to be modified by other programs while it's being read. That's because any changes made to the file on disk are immediately reflected in the memory contents. This breaks Rust's assumptions on multiple levels.

First, in many places Rust relies on the memory contents not changing while borrowed. For example `&str` is checked for UTF-8 validity once; if the contents change later, it can switch to containing invalid UTF-8 and violate memory safety.

Even more fundamentally, exposing a memory-mapped file as `&[u8]` like the `memmap2` crate does is fundamentally unsound if the file ever changes. That's because the contents of `&[u8]` are supposed to never change while the reference exists, and the compiler makes optimizations based on that assumption. Changing the bytes of a `&[u8]` is instant undefined behavior.

I believe it could be used safely on Windows which has mandatory locking, i.e. you can prevent other programs from changing the file while your program is accessing it. There is no equivalent mechanism on Unix platforms, so using `memmap2` crate safely is straight-up impossible. The wrapper would have to expose something like `&[Cell<u8>]`, or perhaps even stronger restrictions (raw pointers with `read_volatile` or perhaps atomics).

**Comment by Shnatsel** [comment]
There's also the question of whether this is even worth the trouble.

I've tried running `zune --mmap=always` and `zune --mmap=no` when converting a large JPEG image to PPM, and according to `time` there was no difference in the peak memory usage. `hyperfine` does report an end-to-end speedup of 4% when using `mmap` on a large file. I wonder if I could get a similar speedup through other means?

I've seen that reading to a small-ish buffer and processing the data immediately is much faster than reading the entire thing into memory and then running code against it. I assume this is due to CPU cache effects - the memory bandwidth and latency limitations do not get in the way this way.

**Comment by Shnatsel** [comment]
Hmmm, I see that the decoder crates currently accept the input data as a slice. So the "load into a small buffer repeatedly" approach is not feasible without changes to all the decoders to support streaming.

In the short term I suggest either restricting memory-mapping to Windows and adding locking, or removing it entirely for now. 

In the long term you might want to get these 4% back by adding support for input streaming.

**Comment by etemesi254** [comment]
1. Yes I think it's worth the trouble.

> I've tried running zune --mmap=always and zune --mmap=no when converting a large JPEG image to PPM, and according to time there was no difference in the peak memory usage. hyperfine does report an end-to-end speedup of 4% when using mmap on a large file. I wonder if I could get a similar speedup through other means?

This from my perspective sounds wrong, you can't allocate on one path and use a reference on the other and   they come having used the same memory, probably `time` is wrong or  it records Resident Memory instead of actual allocated memory for each process.

When designing the decoder crates, I had a choice of using Read traits or byte slices.

Read traits may sound more `Rusty` but are performance detriments,  e.g you can have the `tripple buffer` problem(what I call it), e.g when reading from a file that uses the `BufRead` wrapper and buffering input to your small buffer , you have three intermediate buffers.
1. for kernel.
2.  `BufRead` buffer.
3. Your own buffer.

So to prevent  such things I just said all of them will accept a buffer upfront, so that's why I did it that way if you are wondering.

Back to mmap.

> Even more fundamentally, exposing a memory-mapped file as &[u8] like the memmap2 crate does is fundamentally unsound if the file ever changes. That's because the contents of &[u8] are supposed to never change while the reference exists, and the compiler makes optimizations based on that assumption. Changing the bytes of a &[u8] is instant undefined behavior.

Totally valid, but I'd rather again it be an opt in than totally disable it. Remember that JPEG is really good at compression, try loading a huge PPM to a huge ppm and then you may see the difference

**Comment by Shnatsel** [comment]
I'm OK with disabling mmap by default and explicitly documenting the security considerations.

I'd expect PPM inputs to be rare - the typical workload is something like "load image from compressed form, perform some operations, save image to compressed form", otherwise they take too much space on disk. On HDD you even run into issues with the disk being the bottleneck when loading PPM.

**Comment by Shnatsel** [comment]
I agree that the triple buffering is a problem. But it's not that hard to mitigate - just don't use `BufReader`. You can expose convenience functions for loading from file that doesn't use `BufReader`, so people don't have to hand-roll it.

My point is that it's possible to achieve the same performance without `mmap` and all the unsafety it brings by using a streaming interface, as well as lower memory usage (no need to load the entire file into memory) using a streaming interface for the input, and this may be something to consider in the long term.

**Comment by etemesi254** [comment]
> My point is that it's possible to achieve the same performance without mmap and all the unsafety it brings by using a streaming interface, as well as lower memory usage (no need to load the entire file into memory) using a streaming interface for the input, and this may be something to consider in the long term.

Yes, but a streaming interface requires buffering, it would have been amazing to support everything under the sun, but it isn't feasible.

> I'm OK with disabling mmap by default and explicitly documenting the security considerations.

Okay will do.
