### ISSUE TITLE
PNG: a very small percentage of images decoded incorrectly

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#84]
The results from a test run on the manebooru.art database are in. 

There are no decode failures other than `ERROR [zune_bin]  Could not complete workflow, reason png: Error decoding idat chunks Output limit exceeded, set limit was 1073741824 and output size is 107374185` which appears to be legitimate.

However, there are some discrepancies in decoding compared to imagemagick on a total of 70 images out of 600,000. This should hopefully be a representative sample: https://mega.nz/file/tslC1azb#CBg56O8T7uwC1uXBnbcQLjSaYiQALtaCz_b97hXDm3Y

Tested on commit 15e5d6c34dd51f9db6d8b3563da5c59e6d909131. The run on 600,000 images was done on an earlier commit, but I've re-tested everything on the specified commit, which is the latest as of this writing.

**Comment by etemesi254** [comment]
You have images with 1GB idat chunks?

**Comment by etemesi254** [comment]
A summary is that.

There was a bug on tRNS expansion, it's now corrected.

Most of these images are APNG (`ffprobe` will tell you imagemagick's `identify` won't), I am yet to add support for that.

You will get a warning on encountering APNG files informing you that you will only get the first frame (another cool thing was that we gained `--probe` abilities in the command line).

I don't think there are any further errors on PNG but I am not satisfied with some things i.e bit depth expansion, and some allocations we can avoid. I'm going to spend some time fixing those ones and will ping when I'm satisfied with speed and memory use.
