### ISSUE TITLE
JPEG: panic found by fuzzer

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#86]
`thread '<unnamed>' panicked at 'source slice length (2048) does not match destination slice length (4096)', zune-image/zune-jpeg/src/worker.rs:459:31`

File to trigger it: [crash-f15a1f750cff110e0c8a307d914e63aca5c28e33](https://user-images.githubusercontent.com/291257/217905692-25388c00-d24f-41d6-8e30-f9fa687e2777.jpg)

Reproduce with: `cargo +nightly fuzz run --release decode_buffer path/to/crash-f15a1f750cff110e0c8a307d914e63aca5c28e33.jpg`

Tested on commit 995ea83f7b3035a29c2404a01cef6f6d1cf48677

**Comment by etemesi254** [comment]
Fixed and added a test to capture it.
