### ISSUE TITLE
`InflateDecodeErrors` does not implement the `Error` trait

### ISSUE THREAD

**Issue by philpax** [etemesi254/zune-image#88]
Attempting to use the `?` operator on `decode_deflate()` with `anyhow` results in ``the trait bound `InflateDecodeErrors: StdError` is not satisfied``. Is this intentional?

**Comment by etemesi254** [comment]
The library works in a no std environment

And https://doc.rust-lang.org/core/error/index.html is nightly

**Comment by joshtriplett** [comment]
@etemesi254 Would you consider a `std` feature that enables an `impl Error`?

**Comment by etemesi254** [comment]
Done

**Comment by philpax** [comment]
Awesome, thank you!
