### ISSUE TITLE
zune-inflate: possibly too strict limit check

### ISSUE THREAD

**Issue by johannesvollmer** [etemesi254/zune-image#94]
hi!

we observed what might be a bug in zune-inflate (if not, we would still appreciate your input over at https://github.com/johannesvollmer/exrs/issues/202)

the problem is:
setting the decoder limit to the correct byte size results in an error, even though the decoder returns that exact number of bytes when no limit is set.

specifically, we observed the following test to fail:

```rust
#[test]
pub fn exact_limit_decode_zlib(){
    let compressed = std::fs::read("zlib-compressed-binary 393216 bytes.bin").unwrap();
    let options = zune_inflate::DeflateOptions::default().set_limit(393216);
    let mut decoder = zune_inflate::DeflateDecoder::new_with_options(& compressed, options);
    let mut decompressed = decoder.decode_zlib().unwrap(); // panics when a limit is set
    dbg!(decompressed.len()); // prints 393216 when no limit is set
}
```

with this file: [zlib-compressed-binary 393216 bytes.zip](https://github.com/etemesi254/zune-image/files/10901156/zlib-compressed-binary.393216.bytes.zip)
observed in zune-inflate v0.2.3 and v0.2.50

note: decompressed without limit, it results in the following bytes:
[zlib-compressed-binary 393216 bytes decompressed.zip](https://github.com/etemesi254/zune-image/files/10901181/zlib-compressed-binary.393216.bytes.decompressed.zip)

please correct me if i made any mistake :)

**Comment by Shnatsel** [comment]
Thanks for the quick fix! I'll adjust the roundtrip fuzz target to look for these kinds of issues as well.

A new release needs to be published to crates.io for `exrs` to receive the fix.

**Comment by etemesi254** [comment]
Yes, was an error, and fixed.

I was using the length instead of how many bytes were written in the array, sorry for that.

The reason it was so elusive is that the input stream has extra bytes so it was always in the hot loop, the hot loop had that bug, the cold loop did not exhibit it and hence it never got hit in the testing

**Comment by johannesvollmer** [comment]
great to see you reacting so quickly! thanks

**Comment by etemesi254** [comment]
Made 0.2.51 for this, if semver is anything to go by, the fix should happen transparently

**Comment by Shnatsel** [comment]
A quick fuzzing run didn't show any more issues like these.
